// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"zh": &dictionary{index: zhIndex, data: zhData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%s and %s path file conflict":                                                        232,
	"%s sub path is system reserved path, do not allow to use":                            153,
	"%s type not supported":                                                               27,
	"Unnamed Version":                                                                     178,
	"app %d not found":                                                                    50,
	"app %s is not file type":                                                             65,
	"app alias %s already exists":                                                         45,
	"app is nil":                                                                          170,
	"app name %s already exists":                                                          44,
	"app related biz %d is not exist":                                                     52,
	"app spec is nil":                                                                     204,
	"app's type can not be updated":                                                       206,
	"appID can not be 0":                                                                  179,
	"approval has been revoked, invalid tikcet status: %s":                                117,
	"attachment not set":                                                                  141,
	"authorize failed":                                                                    229,
	"batch add templates to template sets failed, err: %s":                                120,
	"batch create contents failed, err: %s":                                               68,
	"batch delete config items failed":                                                    18,
	"batch delete failed":                                                                 22,
	"batch delete groups failed":                                                          20,
	"batch import of KV config failed, err: %v":                                           94,
	"batch recovery config items failed":                                                  19,
	"batch recovery kv failed":                                                            40,
	"batch update app template binding's failed, err: %s":                                 119,
	"batch update app template binding's failed, err: %v":                                 125,
	"biz list is empty":                                                                   113,
	"bizID can not be 0":                                                                  180,
	"business query failed, err: %v":                                                      51,
	"clearing draft area failed, err: %v":                                                 96,
	"client ids is empty":                                                                 17,
	"commit spec's content is empty":                                                      213,
	"config item %s format error":                                                         30,
	"config item %s json format error":                                                    31,
	"config item %s kv type error":                                                        28,
	"config item %s secret hidden error":                                                  33,
	"config item %s secret type error, err: %v":                                           35,
	"config item %s value error":                                                          36,
	"config item %s yaml format error":                                                    32,
	"content id can not set":                                                              218,
	"content signature should be lowercase":                                               220,
	"count app %d's config items failed, err: %v":                                         174,
	"count the number of app configs failed, err: %s":                                     131,
	"count the number of kV files that have not been deleted failed, err: %v":             99,
	"count the number of service configurations failed, err: %s":                          64,
	"create app failed, err: %v":                                                          172,
	"create data failed, err: %v":                                                         171,
	"create directory failed, err: %v":                                                    3,
	"create kv failed, err: %v":                                                           90,
	"create temporary directory failed, err: %v":                                          4,
	"db operation failed":                                                                 137,
	"decompress file failed, exceeding the maximum file limit threshold of %d":            13,
	"decompress the file. The size of file %s exceeds the maximum limit of %s":            5,
	"decompression failed, err: %v":                                                       6,
	"default_val %s is not a number type":                                                 225,
	"delete app failed, err: %v":                                                          49,
	"delete app related resources failed, err: %v":                                        48,
	"delete one app template binding instance by app id failed, err: %s":                  67,
	"delete one app template variable failed, err: %s":                                    69,
	"delete template from template sets failed":                                           41,
	"delete template from template sets failed, err: %v":                                  123,
	"format error, please check the key: %s":                                              29,
	"get 'kv_type' as a string \n\t\tfrom kv.Data failed, err: %v":                        227,
	"get app %d's template binding failed, err: %v":                                       175,
	"get app fail, key: %s, err: %v":                                                      88,
	"get app failed, err: %v":                                                             46,
	"get app template bindings by template set ids, err: %s":                              118,
	"get app template bindings by template set ids, err: %v":                              124,
	"get config item failed, err: %v":                                                     70,
	"get excluded hook failed, err: %s":                                                   84,
	"get excluded kv failed, err: %s":                                                     98,
	"get kv (%d) failed, err: %v":                                                         86,
	"get permission to apply failed, err: %v":                                             230,
	"get records greater than the latest released version failed, err: %v":                76,
	"get reference template set under this app failed, err: %s":                           80,
	"get template binding relationships through business and service IDs failed, err: %s": 79,
	"get template count failed, err: %v":                                                  197,
	"get template failed, err: %v":                                                        190,
	"get template release failed, err: %v":                                                192,
	"get template set count failed, err: %v":                                              195,
	"get template set data failed, err: %s":                                               121,
	"get template set failed, err: %s":                                                    128,
	"get template set failed, err: %v":                                                    194,
	"get the current number of service config items failed, err: %v":                      12,
	"get the latest released version failed, err: %v":                                     72,
	"get the published config failed, err: %v":                                            73,
	"grpc status with details failed, err: %v":                                            231,
	"hook is nil":                      177,
	"hook name %s already exists":      83,
	"id can not be set":                201,
	"id is required":                   0,
	"id should not be set":             139,
	"invalid app id":                   223,
	"invalid argument":                 138,
	"invalid biz id":                   202,
	"invalid commit spec's content id": 212,
	"invalid config item id":           224,
	"invalid content signature, should be config's sha256 value": 219,
	"invalid data-type":                       210,
	"invalid file name":                       1,
	"invalid memo, length should <= 200":      155,
	"invalid name %s, name cannot all be '.'": 164,
	"invalid name %s, there can't be any /":   165,
	"invalid name, length should <= 128":      158,
	"invalid name, length should <= 64":       163,
	"invalid name, length should >= 1":        157,
	"invalid name, length should >= 9 and must start with prefix bk_bscp_ (ignore case)":                                                                      160,
	"invalid name: %s, only allows to include Chinese, English,numbers, underscore (_),hyphen (-), and must start and end with Chinese, English, or a number": 162,
	"invalid name: %s, only allows to include english、numbers、underscore (_), and must start with prefix bk_bscp_ (ignore case)":                              161,
	"invalid name: %s, only allows to include english、numbers、underscore (_)、hyphen (-), and must start and end with an english、numbers":                      159,
	"invalid namespace, length should <= 128":                                               167,
	"invalid namespace, length should >= 1":                                                 166,
	"invalid origin content signature, should be config's sha256 value":                     221,
	"invalid path %s, length should <= 1024":                                                144,
	"invalid path %s, length should >= 1":                                                   143,
	"invalid path %s, the path must start with '/'":                                         145,
	"invalid path %s, the pathcannot contain consecutive '/'":                               146,
	"invalid path, length should <= 256":                                                    148,
	"invalid path, length should >= 1":                                                      147,
	"invalid path,path does not conform to the win file path format specification":          149,
	"invalid publish_status: %s":                                                            104,
	"invalid reload file path, should <= 128":                                               151,
	"invalid spec, is nil":                                                                  203,
	"invalid username, length should <= 32":                                                 169,
	"invalid username, length should >= 1":                                                  168,
	"json format error, err: %v":                                                            25,
	"keys is required":                                                                      39,
	"kv type does not match the data type defined in the application":                       89,
	"list app template bindings by app ids failed, err: %s":                                 127,
	"list apps by app ids failed, err: %s":                                                  130,
	"list config item failed, err: %v":                                                      11,
	"list kv failed, err: %v":                                                               93,
	"list template config failed, err: %v":                                                  8,
	"list template revisions failed, err: %v":                                               61,
	"list template sets by template set ids failed, err: %s":                                81,
	"list template sets by template set ids failed, err: %v":                                54,
	"list template spaces failed, err: %v":                                                  56,
	"list templates by tuple failed, err: %v":                                               126,
	"list templates data failed, err: %s":                                                   133,
	"list templates failed, err: %v":                                                        15,
	"list templates of template set failed, err: %v":                                        59,
	"list templates revisions data failed, err: %s":                                         135,
	"memo is required, can not be empty":                                                    154,
	"no permission to approve":                                                              110,
	"no permission to revoke":                                                               106,
	"not a KV type service":                                                                 92,
	"not legal JSON data":                                                                   24,
	"not support table config type for now":                                                 207,
	"obtain the number of configuration items":                                              78,
	"origin content signature should be lowercase":                                          222,
	"pass not allowed, current publish status is: %s":                                       111,
	"please set a password":                                                                 37,
	"publish not allowed, current publish status is: %s":                                    112,
	"read file failed, err: %v":                                                             2,
	"reason can not empty":                                                                  109,
	"recover config item failed, err: %v":                                                   75,
	"recovery failed. A file with the same path exists and is not in a new state":           74,
	"rejected not allowed, current publish status is: %s":                                   108,
	"release %s is deprecated, can not be revoke":                                           103,
	"release %s is deprecated, can not be submited":                                         101,
	"release name %s already exists":                                                        105,
	"reload file path is not the absolute path":                                             152,
	"reload file path is required":                                                          150,
	"remove the template set bound to the app failed, err: %s":                              82,
	"resource name '%s' is prefixed with '%s' is reserved name, which is not allows to use": 156,
	"retrieve the referenced script failed, err: %s":                                        85,
	"revision not set":                                                                      142,
	"revoked not allowed, current publish status is: %s":                                    107,
	"same template variable name %s already exists":                                         136,
	"save kv failed":                                                                        97,
	"sensitive data is not visible, unable to view actual content":                          23,
	"sensitive information cannot be exported":                                              16,
	"spec not set":             140,
	"spec should be set":       211,
	"template %d is not exist": 189,
	"template data is empty":   134,
	"template id in %v is not belong to template set id %d": 200,
	"template id in %v is not exist":                        184,
	"template release %d is not exist":                      191,
	"template revision id in %v is not exist":               186,
	"template set %d is not exist":                          193,
	"template set %s not found":                             58,
	"template set data is empty":                            132,
	"template set id in %v is not exist":                    188,
	"template space %s not found":                           57,
	"template space id in %v is not exist":                  183,
	"template variable name must start with %s":             42,
	"template version %s in template file %s \n\t\t\t\thas been removed. Please import the set again": 62,
	"the certificate format is incorrect, only X.509 format is supported":                             38,
	"the config file %s already exists in this space and cannot be created again":                     53,
	"the config item %s under this service already exists and cannot be created again":                87,
	"the data has not been deleted":                                                                              71,
	"the key type for config item %s cannot be empty":                                                            34,
	"the length of hook ids is %d, it must be within the range of [1,%d]":                                        21,
	"the length of template variable ids is %d, it must be within the range of [1,%d]":                           43,
	"the specified type does not match the actual configuration":                                                 47,
	"the template file %s in the template set \n\t\t\t\t%s has been removed. Please import the set again":        60,
	"the total number of app %d's config items(including template and non-template)exceeded the limit %d":        176,
	"the total number of app %s config items(including template and non-template)exceeded the limit %d":          66,
	"the total number of config items exceeded the limit %d":                                                     100,
	"the total number of config items(including template and non-template) \n\t\t\texceeded the limit %d":        77,
	"the total number of template set %d's templates exceeded the limit %d":                                      181,
	"the total number of template set %s templates exceeded the limit %d":                                        129,
	"the type of config item %s is incorrect":                                                                    95,
	"the version number %s in the template file %s is not the \n\t\tlatest version. Please import the set again": 63,
	"there are template sets under the template space, need to delete them first":                                196,
	"there are templates under the template space, need to delete them first":                                    198,
	"there is a release in publishing currently":                                                                 102,
	"there is no template file under this template set":                                                          122,
	"this ticket has been approved, no further processing is required":                                           114,
	"this ticket has been finished, no further processing is required":                                           116,
	"this ticket has been revoked, no further processing is required":                                            115,
	"unknown config type: %s":                                          205,
	"unsupported app reload type: %s":                                  209,
	"unsupported config type: %s":                                      208,
	"unsupported file format: %s":                                      216,
	"unsupported file mode: %s":                                        217,
	"unsupported variable type: %s":                                    226,
	"update app failed, err: %s":                                       173,
	"update app template binding failed, err: %v":                      55,
	"update kv failed, err: %v":                                        91,
	"upload completed":                                                 9,
	"upload completed, %d failed":                                      10,
	"upload failed, please make sure the file size does not exceed %s": 14,
	"upload file failed, err: %v":                                      7,
	"validate template releases exist failed, err: %v":                 185,
	"validate template sets exist failed, err: %v":                     187,
	"validate templates exist failed, err: %v":                         182,
	"validate templates in a template set failed, err: %v":             199,
	"value type assertion failed, err: %v":                             228,
	"verify Unix file paths failed, path: %s, err: %v":                 215,
	"verify Windows file paths failed, path: %s, err: %v":              214,
	"yaml format error, err: %v":                                       26,
}

var enIndex = []uint32{ // 234 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000f, 0x00000021, 0x0000003e,
	0x00000062, 0x00000090, 0x000000df, 0x00000100,
	0x0000011f, 0x00000147, 0x00000158, 0x00000177,
	0x0000019b, 0x000001dd, 0x00000229, 0x0000026d,
	0x0000028f, 0x000002b8, 0x000002cc, 0x000002ed,
	0x00000310, 0x0000032b, 0x00000375, 0x00000389,
	0x000003c6, 0x000003da, 0x000003f8, 0x00000416,
	0x0000042f, 0x0000044f, 0x00000479, 0x00000498,
	// Entry 20 - 3F
	0x000004bc, 0x000004e0, 0x00000506, 0x00000539,
	0x00000569, 0x00000587, 0x0000059d, 0x000005e1,
	0x000005f2, 0x0000060b, 0x00000635, 0x00000662,
	0x000006b9, 0x000006d7, 0x000006f6, 0x00000711,
	0x0000074c, 0x0000077c, 0x0000079a, 0x000007ae,
	0x000007d0, 0x000007f3, 0x00000842, 0x0000087c,
	0x000008ab, 0x000008d3, 0x000008f2, 0x0000090f,
	0x00000941, 0x000009a6, 0x000009d1, 0x00000a32,
	// Entry 40 - 5F
	0x00000aa0, 0x00000ade, 0x00000af9, 0x00000b61,
	0x00000ba7, 0x00000bd0, 0x00000c04, 0x00000c27,
	0x00000c45, 0x00000c78, 0x00000ca4, 0x00000cf0,
	0x00000d17, 0x00000d5f, 0x00000dc2, 0x00000deb,
	0x00000e42, 0x00000e7f, 0x00000eb9, 0x00000ef5,
	0x00000f14, 0x00000f39, 0x00000f6b, 0x00000f8d,
	0x00000fe1, 0x00001006, 0x00001046, 0x00001063,
	0x00001080, 0x00001096, 0x000010b1, 0x000010de,
	// Entry 60 - 7F
	0x00001109, 0x00001130, 0x0000113f, 0x00001162,
	0x000011ad, 0x000011e7, 0x00001218, 0x00001243,
	0x00001272, 0x00001290, 0x000012b2, 0x000012ca,
	0x00001300, 0x00001337, 0x0000134c, 0x00001365,
	0x00001398, 0x000013ce, 0x000013e0, 0x00001421,
	0x00001461, 0x000014a2, 0x000014da, 0x00001514,
	0x0000154b, 0x00001583, 0x000015ac, 0x000015de,
	0x00001614, 0x0000164e, 0x00001685, 0x000016b0,
	// Entry 80 - 9F
	0x000016e9, 0x0000170d, 0x00001757, 0x0000177f,
	0x000017b2, 0x000017cd, 0x000017f4, 0x0000180b,
	0x0000183c, 0x0000186d, 0x00001881, 0x00001892,
	0x000018a7, 0x000018b4, 0x000018c7, 0x000018d8,
	0x000018ff, 0x00001929, 0x0000195a, 0x00001995,
	0x000019b6, 0x000019d9, 0x00001a26, 0x00001a43,
	0x00001a6b, 0x00001a95, 0x00001ad1, 0x00001af4,
	0x00001b17, 0x00001b73, 0x00001b94, 0x00001bb7,
	// Entry A0 - BF
	0x00001c45, 0x00001c98, 0x00001d1a, 0x00001db5,
	0x00001dd7, 0x00001e02, 0x00001e2b, 0x00001e51,
	0x00001e79, 0x00001e9e, 0x00001ec4, 0x00001ecf,
	0x00001eee, 0x00001f0c, 0x00001f2a, 0x00001f5c,
	0x00001f90, 0x00001ffa, 0x00002006, 0x00002016,
	0x00002029, 0x0000203c, 0x00002088, 0x000020b4,
	0x000020dc, 0x000020fe, 0x00002132, 0x0000215d,
	0x0000218d, 0x000021b3, 0x000021cf, 0x000021ef,
	// Entry C0 - DF
	0x00002213, 0x0000223b, 0x0000225b, 0x0000227f,
	0x000022a9, 0x000022f5, 0x0000231b, 0x00002363,
	0x0000239b, 0x000023d7, 0x000023e9, 0x000023f8,
	0x0000240d, 0x0000241d, 0x00002438, 0x00002456,
	0x0000247c, 0x0000249b, 0x000024be, 0x000024d0,
	0x000024e3, 0x00002504, 0x00002523, 0x0000255d,
	0x00002594, 0x000025b3, 0x000025d0, 0x000025e7,
	0x00002622, 0x00002648, 0x0000268a, 0x000026b7,
	// Entry E0 - FF
	0x000026c6, 0x000026dd, 0x00002704, 0x00002725,
	0x00002762, 0x0000278a, 0x0000279b, 0x000027c6,
	0x000027f2, 0x00002815,
} // Size: 960 bytes

const enData string = "" + // Size: 10261 bytes
	"\x02id is required\x02invalid file name\x02read file failed, err: %[1]v" +
	"\x02create directory failed, err: %[1]v\x02create temporary directory fa" +
	"iled, err: %[1]v\x02decompress the file. The size of file %[1]s exceeds " +
	"the maximum limit of %[2]s\x02decompression failed, err: %[1]v\x02upload" +
	" file failed, err: %[1]v\x02list template config failed, err: %[1]v\x02u" +
	"pload completed\x02upload completed, %[1]d failed\x02list config item fa" +
	"iled, err: %[1]v\x02get the current number of service config items faile" +
	"d, err: %[1]v\x02decompress file failed, exceeding the maximum file limi" +
	"t threshold of %[1]d\x02upload failed, please make sure the file size do" +
	"es not exceed %[1]s\x02list templates failed, err: %[1]v\x02sensitive in" +
	"formation cannot be exported\x02client ids is empty\x02batch delete conf" +
	"ig items failed\x02batch recovery config items failed\x02batch delete gr" +
	"oups failed\x02the length of hook ids is %[1]d, it must be within the ra" +
	"nge of [1,%[2]d]\x02batch delete failed\x02sensitive data is not visible" +
	", unable to view actual content\x02not legal JSON data\x02json format er" +
	"ror, err: %[1]v\x02yaml format error, err: %[1]v\x02%[1]s type not suppo" +
	"rted\x02config item %[1]s kv type error\x02format error, please check th" +
	"e key: %[1]s\x02config item %[1]s format error\x02config item %[1]s json" +
	" format error\x02config item %[1]s yaml format error\x02config item %[1]" +
	"s secret hidden error\x02the key type for config item %[1]s cannot be em" +
	"pty\x02config item %[1]s secret type error, err: %[2]v\x02config item %[" +
	"1]s value error\x02please set a password\x02the certificate format is in" +
	"correct, only X.509 format is supported\x02keys is required\x02batch rec" +
	"overy kv failed\x02delete template from template sets failed\x02template" +
	" variable name must start with %[1]s\x02the length of template variable " +
	"ids is %[1]d, it must be within the range of [1,%[2]d]\x02app name %[1]s" +
	" already exists\x02app alias %[1]s already exists\x02get app failed, err" +
	": %[1]v\x02the specified type does not match the actual configuration" +
	"\x02delete app related resources failed, err: %[1]v\x02delete app failed" +
	", err: %[1]v\x02app %[1]d not found\x02business query failed, err: %[1]v" +
	"\x02app related biz %[1]d is not exist\x02the config file %[1]s already " +
	"exists in this space and cannot be created again\x02list template sets b" +
	"y template set ids failed, err: %[1]v\x02update app template binding fai" +
	"led, err: %[1]v\x02list template spaces failed, err: %[1]v\x02template s" +
	"pace %[1]s not found\x02template set %[1]s not found\x02list templates o" +
	"f template set failed, err: %[1]v\x02the template file %[1]s in the temp" +
	"late set \x0a\x09\x09\x09\x09%[2]s has been removed. Please import the s" +
	"et again\x02list template revisions failed, err: %[1]v\x02template versi" +
	"on %[1]s in template file %[2]s \x0a\x09\x09\x09\x09has been removed. Pl" +
	"ease import the set again\x02the version number %[1]s in the template fi" +
	"le %[2]s is not the \x0a\x09\x09latest version. Please import the set ag" +
	"ain\x02count the number of service configurations failed, err: %[1]s\x02" +
	"app %[1]s is not file type\x02the total number of app %[1]s config items" +
	"(including template and non-template)exceeded the limit %[2]d\x02delete " +
	"one app template binding instance by app id failed, err: %[1]s\x02batch " +
	"create contents failed, err: %[1]s\x02delete one app template variable f" +
	"ailed, err: %[1]s\x02get config item failed, err: %[1]v\x02the data has " +
	"not been deleted\x02get the latest released version failed, err: %[1]v" +
	"\x02get the published config failed, err: %[1]v\x02recovery failed. A fi" +
	"le with the same path exists and is not in a new state\x02recover config" +
	" item failed, err: %[1]v\x02get records greater than the latest released" +
	" version failed, err: %[1]v\x02the total number of config items(includin" +
	"g template and non-template) \x0a\x09\x09\x09exceeded the limit %[1]d" +
	"\x02obtain the number of configuration items\x02get template binding rel" +
	"ationships through business and service IDs failed, err: %[1]s\x02get re" +
	"ference template set under this app failed, err: %[1]s\x02list template " +
	"sets by template set ids failed, err: %[1]s\x02remove the template set b" +
	"ound to the app failed, err: %[1]s\x02hook name %[1]s already exists\x02" +
	"get excluded hook failed, err: %[1]s\x02retrieve the referenced script f" +
	"ailed, err: %[1]s\x02get kv (%[1]d) failed, err: %[2]v\x02the config ite" +
	"m %[1]s under this service already exists and cannot be created again" +
	"\x02get app fail, key: %[1]s, err: %[2]v\x02kv type does not match the d" +
	"ata type defined in the application\x02create kv failed, err: %[1]v\x02u" +
	"pdate kv failed, err: %[1]v\x02not a KV type service\x02list kv failed, " +
	"err: %[1]v\x02batch import of KV config failed, err: %[1]v\x02the type o" +
	"f config item %[1]s is incorrect\x02clearing draft area failed, err: %[1" +
	"]v\x02save kv failed\x02get excluded kv failed, err: %[1]s\x02count the " +
	"number of kV files that have not been deleted failed, err: %[1]v\x02the " +
	"total number of config items exceeded the limit %[1]d\x02release %[1]s i" +
	"s deprecated, can not be submited\x02there is a release in publishing cu" +
	"rrently\x02release %[1]s is deprecated, can not be revoke\x02invalid pub" +
	"lish_status: %[1]s\x02release name %[1]s already exists\x02no permission" +
	" to revoke\x02revoked not allowed, current publish status is: %[1]s\x02r" +
	"ejected not allowed, current publish status is: %[1]s\x02reason can not " +
	"empty\x02no permission to approve\x02pass not allowed, current publish s" +
	"tatus is: %[1]s\x02publish not allowed, current publish status is: %[1]s" +
	"\x02biz list is empty\x02this ticket has been approved, no further proce" +
	"ssing is required\x02this ticket has been revoked, no further processing" +
	" is required\x02this ticket has been finished, no further processing is " +
	"required\x02approval has been revoked, invalid tikcet status: %[1]s\x02g" +
	"et app template bindings by template set ids, err: %[1]s\x02batch update" +
	" app template binding's failed, err: %[1]s\x02batch add templates to tem" +
	"plate sets failed, err: %[1]s\x02get template set data failed, err: %[1]" +
	"s\x02there is no template file under this template set\x02delete templat" +
	"e from template sets failed, err: %[1]v\x02get app template bindings by " +
	"template set ids, err: %[1]v\x02batch update app template binding's fail" +
	"ed, err: %[1]v\x02list templates by tuple failed, err: %[1]v\x02list app" +
	" template bindings by app ids failed, err: %[1]s\x02get template set fai" +
	"led, err: %[1]s\x02the total number of template set %[1]s templates exce" +
	"eded the limit %[2]d\x02list apps by app ids failed, err: %[1]s\x02count" +
	" the number of app configs failed, err: %[1]s\x02template set data is em" +
	"pty\x02list templates data failed, err: %[1]s\x02template data is empty" +
	"\x02list templates revisions data failed, err: %[1]s\x02same template va" +
	"riable name %[1]s already exists\x02db operation failed\x02invalid argum" +
	"ent\x02id should not be set\x02spec not set\x02attachment not set\x02rev" +
	"ision not set\x02invalid path %[1]s, length should >= 1\x02invalid path " +
	"%[1]s, length should <= 1024\x02invalid path %[1]s, the path must start " +
	"with '/'\x02invalid path %[1]s, the pathcannot contain consecutive '/'" +
	"\x02invalid path, length should >= 1\x02invalid path, length should <= 2" +
	"56\x02invalid path,path does not conform to the win file path format spe" +
	"cification\x02reload file path is required\x02invalid reload file path, " +
	"should <= 128\x02reload file path is not the absolute path\x02%[1]s sub " +
	"path is system reserved path, do not allow to use\x02memo is required, c" +
	"an not be empty\x02invalid memo, length should <= 200\x02resource name '" +
	"%[1]s' is prefixed with '%[2]s' is reserved name, which is not allows to" +
	" use\x02invalid name, length should >= 1\x02invalid name, length should " +
	"<= 128\x02invalid name: %[1]s, only allows to include english、numbers、un" +
	"derscore (_)、hyphen (-), and must start and end with an english、numbers" +
	"\x02invalid name, length should >= 9 and must start with prefix bk_bscp_" +
	" (ignore case)\x02invalid name: %[1]s, only allows to include english、nu" +
	"mbers、underscore (_), and must start with prefix bk_bscp_ (ignore case)" +
	"\x02invalid name: %[1]s, only allows to include Chinese, English,numbers" +
	", underscore (_),hyphen (-), and must start and end with Chinese, Englis" +
	"h, or a number\x02invalid name, length should <= 64\x02invalid name %[1]" +
	"s, name cannot all be '.'\x02invalid name %[1]s, there can't be any /" +
	"\x02invalid namespace, length should >= 1\x02invalid namespace, length s" +
	"hould <= 128\x02invalid username, length should >= 1\x02invalid username" +
	", length should <= 32\x02app is nil\x02create data failed, err: %[1]v" +
	"\x02create app failed, err: %[1]v\x02update app failed, err: %[1]s\x02co" +
	"unt app %[1]d's config items failed, err: %[2]v\x02get app %[1]d's templ" +
	"ate binding failed, err: %[2]v\x02the total number of app %[1]d's config" +
	" items(including template and non-template)exceeded the limit %[2]d\x02h" +
	"ook is nil\x02Unnamed Version\x02appID can not be 0\x02bizID can not be " +
	"0\x02the total number of template set %[1]d's templates exceeded the lim" +
	"it %[2]d\x02validate templates exist failed, err: %[1]v\x02template spac" +
	"e id in %[1]v is not exist\x02template id in %[1]v is not exist\x02valid" +
	"ate template releases exist failed, err: %[1]v\x02template revision id i" +
	"n %[1]v is not exist\x02validate template sets exist failed, err: %[1]v" +
	"\x02template set id in %[1]v is not exist\x02template %[1]d is not exist" +
	"\x02get template failed, err: %[1]v\x02template release %[1]d is not exi" +
	"st\x02get template release failed, err: %[1]v\x02template set %[1]d is n" +
	"ot exist\x02get template set failed, err: %[1]v\x02get template set coun" +
	"t failed, err: %[1]v\x02there are template sets under the template space" +
	", need to delete them first\x02get template count failed, err: %[1]v\x02" +
	"there are templates under the template space, need to delete them first" +
	"\x02validate templates in a template set failed, err: %[1]v\x02template " +
	"id in %[1]v is not belong to template set id %[2]d\x02id can not be set" +
	"\x02invalid biz id\x02invalid spec, is nil\x02app spec is nil\x02unknown" +
	" config type: %[1]s\x02app's type can not be updated\x02not support tabl" +
	"e config type for now\x02unsupported config type: %[1]s\x02unsupported a" +
	"pp reload type: %[1]s\x02invalid data-type\x02spec should be set\x02inva" +
	"lid commit spec's content id\x02commit spec's content is empty\x02verify" +
	" Windows file paths failed, path: %[1]s, err: %[2]v\x02verify Unix file " +
	"paths failed, path: %[1]s, err: %[2]v\x02unsupported file format: %[1]s" +
	"\x02unsupported file mode: %[1]s\x02content id can not set\x02invalid co" +
	"ntent signature, should be config's sha256 value\x02content signature sh" +
	"ould be lowercase\x02invalid origin content signature, should be config'" +
	"s sha256 value\x02origin content signature should be lowercase\x02invali" +
	"d app id\x02invalid config item id\x02default_val %[1]s is not a number " +
	"type\x02unsupported variable type: %[1]s\x02get 'kv_type' as a string " +
	"\x0a\x09\x09from kv.Data failed, err: %[1]v\x02value type assertion fail" +
	"ed, err: %[1]v\x02authorize failed\x02get permission to apply failed, er" +
	"r: %[1]v\x02grpc status with details failed, err: %[1]v\x02%[1]s and %[2" +
	"]s path file conflict"

var zhIndex = []uint32{ // 234 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000f, 0x00000022, 0x00000041,
	0x00000060, 0x00000085, 0x000000d1, 0x000000ea,
	0x00000109, 0x0000012e, 0x0000013b, 0x00000156,
	0x00000178, 0x000001ac, 0x000001ee, 0x00000221,
	0x00000246, 0x0000025f, 0x00000273, 0x0000028f,
	0x0000028f, 0x000002a8, 0x000002e8, 0x000002fb,
	0x0000032c, 0x00000340, 0x00000361, 0x00000382,
	0x00000398, 0x000003b5, 0x000003d8, 0x000003f5,
	// Entry 20 - 3F
	0x00000416, 0x00000437, 0x00000466, 0x00000492,
	0x000004c1, 0x000004db, 0x000004eb, 0x00000517,
	0x00000517, 0x00000517, 0x00000517, 0x00000541,
	0x00000587, 0x000005a4, 0x000005c1, 0x000005e0,
	0x00000608, 0x00000633, 0x00000652, 0x0000066f,
	0x0000068e, 0x000006b4, 0x000006f1, 0x00000727,
	0x00000752, 0x00000777, 0x00000794, 0x000007b1,
	0x000007e2, 0x0000082f, 0x00000854, 0x000008a1,
	// Entry 40 - 5F
	0x000008f4, 0x0000091f, 0x00000942, 0x000009b3,
	0x000009de, 0x00000a03, 0x00000a28, 0x00000a4a,
	0x00000a63, 0x00000a8e, 0x00000ab9, 0x00000b05,
	0x00000b27, 0x00000b61, 0x00000bad, 0x00000bc3,
	0x00000c05, 0x00000c3c, 0x00000c72, 0x00000c91,
	0x00000cae, 0x00000cd9, 0x00000d01, 0x00000d26,
	0x00000d61, 0x00000d8c, 0x00000dc6, 0x00000de1,
	0x00000dfc, 0x00000e14, 0x00000e35, 0x00000e5c,
	// Entry 60 - 7F
	0x00000e7f, 0x00000ea1, 0x00000eb0, 0x00000ed7,
	0x00000ed7, 0x00000ed7, 0x00000efb, 0x00000f14,
	0x00000f38, 0x00000f53, 0x00000f6e, 0x00000f81,
	0x00000fb1, 0x00000fde, 0x00000ff1, 0x00001001,
	0x0000102e, 0x0000105e, 0x00001071, 0x000010a2,
	0x000010cd, 0x000010f8, 0x0000112a, 0x00001163,
	0x00001194, 0x000011c2, 0x000011ea, 0x0000120c,
	0x0000123d, 0x00001276, 0x000012a7, 0x000012c6,
	// Entry 80 - 9F
	0x000012fc, 0x0000131e, 0x00001365, 0x0000138f,
	0x000013ba, 0x000013d3, 0x000013f8, 0x0000140b,
	0x00001436, 0x00001460, 0x0000146f, 0x0000147c,
	0x00001491, 0x000014a5, 0x000014bf, 0x000014d7,
	0x000014ff, 0x0000152a, 0x0000155d, 0x00001596,
	0x000015b6, 0x000015d8, 0x00001611, 0x00001630,
	0x0000165e, 0x00001689, 0x000016bf, 0x000016e0,
	0x00001702, 0x00001753, 0x00001773, 0x00001793,
	// Entry A0 - BF
	0x0000181a, 0x0000186d, 0x000018e6, 0x0000197f,
	0x000019a0, 0x000019d2, 0x000019f4, 0x00001a1a,
	0x00001a42, 0x00001a65, 0x00001a89, 0x00001a96,
	0x00001aaf, 0x00001ace, 0x00001aed, 0x00001b1f,
	0x00001b55, 0x00001ba5, 0x00001bb5, 0x00001bc5,
	0x00001bd5, 0x00001bd5, 0x00001c1e, 0x00001c49,
	0x00001c6f, 0x00001c8f, 0x00001cc0, 0x00001ce6,
	0x00001d17, 0x00001d3d, 0x00001d54, 0x00001d73,
	// Entry C0 - DF
	0x00001d90, 0x00001db5, 0x00001dd2, 0x00001df4,
	0x00001e1f, 0x00001e4f, 0x00001e74, 0x00001e9e,
	0x00001ecf, 0x00001f04, 0x00001f14, 0x00001f29,
	0x00001f36, 0x00001f49, 0x00001f67, 0x00001f80,
	0x00001f9c, 0x00001fbd, 0x00001fde, 0x00001ff7,
	0x00002004, 0x00002017, 0x00002024, 0x0000205f,
	0x00002097, 0x000020b8, 0x000020d9, 0x000020e6,
	0x00002115, 0x0000212b, 0x00002163, 0x0000217f,
	// Entry E0 - FF
	0x00002191, 0x000021a6, 0x000021cb, 0x000021ec,
	0x0000222d, 0x0000224f, 0x0000225c, 0x0000227b,
	0x000022a5, 0x000022c8,
} // Size: 960 bytes

const zhData string = "" + // Size: 8904 bytes
	"\x02id不能为空\x02无效的文件名\x02读取文件失败, err: %[1]v\x02创建目录失败, err: %[1]v\x02创建临时" +
	"目录失败, err: %[1]v\x02解压文件失败, 文件 %[1]s 的大小超过了最大限制阈值 %[2]s\x02解压失败, err: " +
	"%[1]v\x02上传文件失败, err: %[1]v\x02获取模板配置失败, err: %[1]v\x02上传完成\x02上传完成, %[1" +
	"]d 失败\x02获取配置项失败, err: %[1]v\x02获取当前服务配置项总数失败, err: %[1]v\x02解压文件失败, 超过了" +
	"文件数量最大限制阈值 %[1]d\x02上传失败, 请确保文件大小不超过 %[1]s\x02获取模板数据失败, err: %[1]v\x02" +
	"敏感信息无法导出\x02客户端 id 为空\x02批量删除配置项失败\x02批量删除群组失败\x02脚本id列表的长度为%[1]d, 长度范" +
	"围必须为[1,%[2]d]\x02批量删除失败\x02敏感数据不可见，无法查看实际内容\x02JSON数据不合法\x02json 格式化错误" +
	", err: %[1]v\x02yaml 格式化错误, err: %[1]v\x02%[1]s 类型不支持\x02配置项 %[1]s 类型错误" +
	"\x02格式错误, 请检查键：%[1]s\x02配置项 %[1]s 格式错误\x02配置项 %[1]s json格式错误\x02配置项 %[1]" +
	"s yaml格式错误\x02配置项 %[1]s 密钥是否显示设置错误\x02配置项 %[1]s 的密钥类型不能为空\x02配置项 %[1]s 密" +
	"钥类型错误, err: %[2]v\x02配置项 %[1]s 值错误\x02请设置密码\x02证书格式不正确, 仅支持X.509格式\x02" +
	"模版变量名必须以%[1]s前缀开头\x02全局变量id列表的长度为%[1]d, 长度范围必须为[1,%[2]d]\x02服务名称 %[1]s" +
	" 已存在\x02服务别名 %[1]s 已存在\x02获取服务失败, err: %[1]v\x02指定的类型与实际配置不匹配\x02删除服务相关资" +
	"源失败, err: %[1]v\x02删除服务失败, err: %[1]v\x02ID为%[1]d的服务不存在\x02业务查询失败, err" +
	": %[1]v\x02服务相关的业务 %[1]d 不存在\x02此空间下配置文件 %[1]s 已存在, 无法重复创建\x02按模板套餐ID列出模" +
	"板套餐失败, err: %[1]v\x02更新服务模板绑定失败, err: %[1]v\x02列出模板空间失败, err: %[1]v" +
	"\x02模板空间 %[1]s 不存在\x02模板套餐 %[1]s 不存在\x02获取模板套餐下的模板失败, err: %[1]v\x02模板套餐" +
	" %[2]s 中的模板文件 %[1]s 被移除, 请重新导入套餐\x02获取模板版本失败, err: %[1]v\x02模板文件 %[2]s 中" +
	"的模板版本 %[1]s 被移除, 请重新导入套餐\x02模板文件 %[2]s 中的版本号 %[1]s 不是最新版本, 请重新导入套餐\x02" +
	"统计服务配置数量失败, err: %[1]s\x02该服务 %[1]s 不是文件类型\x02服务 %[1]s 的配置项总数（包括模板和非模板" +
	"）超过单服务最大配置文件数量限制 %[2]d\x02移除服务模板套餐失败, err: %[1]s\x02批量创建内容失败, err: %[1" +
	"]s\x02删除模板变量失败, err: %[1]s\x02获取配置项失败, err: %[1]v\x02配置项没有被删除\x02获取最新发布版" +
	"本失败, err: %[1]v\x02获取已发布的配置失败, err: %[1]v\x02恢复失败。具有相同路径的文件已存在，但未处于新状态" +
	"\x02恢复配置项失败, err: %[1]v\x02获取大于最新发布版本的记录失败, err: %[1]v\x02该服务配置项的总数（包括模板" +
	"和非模板）超出限制 %[1]d\x02获取配置项数量\x02通过业务和服务ID获取模板绑定关系失败, err: %[1]s\x02获取该服务" +
	"下的引用模板集失败, err: %[1]s\x02按模板套餐ID列出模板套餐失败, err: %[1]s\x02移除套餐失败, err: %" +
	"[1]s\x02脚本名称 %[1]s 已存在\x02获取排除后的脚本失败, err: %[1]s\x02检索引用的脚本失败, err: %[1]" +
	"s\x02获取 kv (%[1]d) 失败, err: %[2]v\x02该服务下的配置项%[1]s已存在, 无法重复创建\x02获取服务失败," +
	" key: %[1]s, err: %[2]v\x02kv 类型与服务类型中定义的数据类型不匹配\x02创建kv失败, err: %[1]v" +
	"\x02更新kv失败, err: %[1]v\x02不是kv类型的服务\x02获取kv列表失败, err: %[1]v\x02批量导入KV配置失" +
	"败, err: %[1]v\x02配置项 %[1]s 的类型不正确\x02清除草稿区失败, err: %[1]v\x02kv保持失败\x02" +
	"获取排除后的kv失败, err: %[1]s\x02版本%[1]s已弃用，无法提交\x02当前有版本在上线\x02版本%[1]s已弃用，无法" +
	"撤消\x02上线状态无效：%[1]s\x02版本名称%[1]s已存在\x02没有撤销权限\x02不允许撤销，当前上线状态为：%[1]s" +
	"\x02无法拒绝，当前上线状态为：%[1]s\x02原因不能为空\x02无权限审批\x02无法通过，当前上线状态为：%[1]s\x02不允许上线" +
	"，当前上线状态为：%[1]s\x02业务列表为空\x02此单据已审批完成，无需进一步处理\x02此单据已撤销，无需进一步处理\x02此单据已" +
	"结束，无需进一步处理\x02此单据已撤销，无效的单据状态: %[1]s\x02按模板集ID获取应用程序模板绑定, err: %[1]s" +
	"\x02批量更新应用模板绑定失败, err: %[1]s\x02模板集批量添加模板失败, err: %[1]s\x02获取模板集数据失败, er" +
	"r: %[1]s\x02此模板集下没有模板文件\x02从模板套餐中删除模板失败, err: %[1]v\x02按模板集ID获取应用程序模板绑定," +
	" err: %[1]v\x02批量更新应用模板绑定失败, err: %[1]v\x02列出模板失败, err: %[1]v\x02按服务ID列出" +
	"应用模板绑定失败, err: %[1]s\x02获取模板集失败, err: %[1]s\x02模板套餐 %[1]s 超过单套餐最大配置文件数" +
	"量限制 %[2]d\x02按服务ID列出服务失败, err: %[1]s\x02统计服务配置数量失败, err: %[1]s\x02模板套餐" +
	"数据为空\x02列出模板数据失败, err: %[1]s\x02模板数据为空\x02列出模板版本数据失败, err: %[1]s\x02同名" +
	"的模版变量名称%[1]s已存在\x02db操作失败\x02无效参数\x02id不应该被设置\x02spec没有被设置\x02attachme" +
	"nt没有被设置\x02revision没有被设置\x02路径 %[1]s 无效，长度应为 >= 1\x02路径 %[1]s 无效，长度应为 <=" +
	" 1024\x02路径 %[1]s 无效，路径必须以“/”开头\x02路径 %[1]s 无效，路径不能包含连续的“/”\x02路径无效, 长度应" +
	"为 >= 1\x02路径无效, 长度应为 <= 256\x02路径无效, 路径不符合win文件路径格式规范\x02需要重新加载文件路径" +
	"\x02重新加载文件路径无效, 应该 <= 128\x02重新加载文件路径不是绝对路径\x02%[1]s 子路径为系统保留路径, 不允许使用" +
	"\x02描述为必填项, 不能为空\x02描述无效, 长度应为 <= 200\x02资源名称“%[1]s”以“%[2]s”为前缀, 是保留名称, " +
	"不允许使用\x02名称无效, 长度应为 >= 1\x02无效名称, 长度应该<=128\x02无效名称：%[1]s, 只允许包含英文、数字、" +
	"下划线（_）、连字符（-）, 且必须以英文、数字开头和结尾\x02无效名称, 长度应该>=9且必须以bk_bscp_前缀开头（忽略大小写）" +
	"\x02无效名称：%[1]s, 只允许英文、数字、下划线（_）, 且必须以bk_bscp_前缀开头（忽略大小写）\x02无效名称：%[1]s, " +
	"只允许包含中文、英文、数字、下划线（_）、连字符（-）, 且必须以中文、英文或数字开头和结尾\x02名称无效, 长度应为 <= 64\x02" +
	"名称 %[1]s 无效, 名称不能全部为“.”\x02名称 %[1]s 无效，不能有 /\x02命名空间无效, 长度应为 >= 1\x02命" +
	"名空间无效, 长度应为 <= 128\x02用户名无效, 长度应为 >= 1\x02用户名无效, 长度应为 <= 32\x02服务为空" +
	"\x02创建失败, err: %[1]v\x02创建服务失败, err: %[1]v\x02更新服务失败, err: %[1]s\x02统计服务" +
	" %[1]d 的配置项失败, err: %[2]v\x02获取服务 %[1]d 的模板绑定失败,  err: %[2]v\x02服务 %[1]d" +
	" 的配置项总数（包括模板和非模板）超出限制 %[2]d\x02脚本不存在\x02未命名版本\x02appID不能为0\x02模板套餐 %[1]d" +
	"'s 超过单套餐最大配置文件数量限制 %[2]d\x02验证模板是否存在失败, err: %[1]v\x02%[1]v 中的模板空间 ID 不存" +
	"在\x02%[1]v 中的模板 ID 不存在\x02验证模板版本是否存在失败, err: %[1]v\x02%[1]v 中的模板版本 ID " +
	"不存在\x02验证模板套餐是否存在失败, err: %[1]v\x02%[1]v 中的模板套餐 ID 不存在\x02模板 %[1]d 不存在" +
	"\x02获取模板失败, err: %[1]v\x02模板版本 %[1]d 不存在\x02获取模板版本失败, err: %[1]v\x02模板套餐" +
	" %[1]d 不存在\x02获取模板集失败, err: %[1]v\x02统计模板套餐数量失败, err: %[1]v\x02模板空间下有模板套" +
	"餐, 需要先删除\x02获取模板数量失败, err: %[1]v\x02模板空间下有模板, 需要先删除\x02验证模板套餐中的模板失败, e" +
	"rr: %[1]v\x02%[1]v 中的模板 ID 不属于模板套餐 ID %[2]d\x02ID 不能为空\x02无法验证业务ID\x02参数" +
	"为空\x02服务参数为空\x02未知的配置类型：%[1]s\x02服务类型不能编辑\x02暂不支持表配置类型\x02不支持的配置类型：%[1" +
	"]s\x02不支持的服务类型：%[1]s\x02无法验证数据类型\x02参数为空\x02无法验证参数\x02参数为空\x02验证 Windows" +
	" 文件路径失败, path: %[1]s, err: %[2]v\x02验证 Unix 文件路径失败, path: %[1]s, err: %[" +
	"2]v\x02不支持的文件格式：%[1]s\x02不支持的文件模式：%[1]s\x02参数为空\x02内容签名无效, 应为配置的 sha256 " +
	"值\x02内容签名应小写\x02无效的原始内容签名, 应为配置的 sha256 值\x02原始内容签名应小写\x02无效的服务ID\x02无" +
	"效的配置项ID\x02default_val %[1]s 不是数字类型\x02不支持的变量类型：%[1]s\x02从 kv.Data 获取“" +
	"kv_type”作为字符串失败, err: %[1]v\x02值类型断言失败, err: %[1]v\x02授权失败\x02获取权限失败, er" +
	"r: %[1]v\x02grpc 状态详细信息失败, err: %[1]v\x02%[1]s 与 %[2]s 路径文件冲突"

	// Total table size 21085 bytes (20KiB); checksum: 5919A07D
