// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"zh": &dictionary{index: zhIndex, data: zhData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%s and %s path file conflict":                             494,
	"%s sub path is system reserved path, do not allow to use": 414,
	"%s type not supported":                                    29,
	"Abnormal":                                                 282,
	"ConfigCheck":                                              477,
	"ConfigFile":                                               466,
	"ConfigGenerate":                                           476,
	"ConfigPublish":                                            475,
	"Deleted":                                                  280,
	"Executing":                                                478,
	"ExecutionFailed":                                          480,
	"ExecutionSuccessful":                                      479,
	"Kill":                                                     472,
	"Managed":                                                  276,
	"Normal":                                                   279,
	"NotRunning":                                               273,
	"PartialFailure":                                           481,
	"PartiallyManaged":                                         278,
	"PartiallyRunning":                                         268,
	"Process":                                                  467,
	"Register":                                                 473,
	"Reload":                                                   471,
	"Reloading":                                                272,
	"Restart":                                                  470,
	"Restarting":                                               270,
	"Running":                                                  267,
	"Start":                                                    468,
	"Starting":                                                 269,
	"StartingManagement":                                       274,
	"Stop":                                                     469,
	"Stopping":                                                 271,
	"StoppingManagement":                                       275,
	"Unmanaged":                                                277,
	"Unnamed Version":                                          367,
	"Unregister":                                               474,
	"Updated":                                                  281,
	"app %d not found":                                         58,
	"app %s is not file type":                                  75,
	"app alias %s already exists":                              53,
	"app does not exist":                                       287,
	"app is nil":                                               353,
	"app name %s already exists":                               52,
	"app query failed":                                         288,
	"app related biz %d is not exist":                          60,
	"app spec is nil":                                          437,
	"app's type can not be updated":                            439,
	"appID can not be 0":                                       368,
	"approval has been revoked, invalid tikcet status: %s": 303,
	"at least one config template group is required":       80,
	"attachment not set":                      402,
	"attachment should be set":                482,
	"authorize failed":                        395,
	"batch %d is not a config generate batch": 117,
	"batch %s has %s failed task(s) (success %s), please regenerate the config before pushing":                 123,
	"batch %s is still running (completed %s), please wait for the config generation to finish before pushing": 122,
	"batch %s total count is 0, there is no task to push":                                                      119,
	"batch add templates to template sets failed, err: %s":                                                     186,
	"batch create contents failed, err: %s":                                                                    156,
	"batch create of KV config failed, err: %v":                                                                62,
	"batch delete config items failed":                                                                         18,
	"batch delete failed":                                                                                      24,
	"batch delete groups failed":                                                                               20,
	"batch import of KV config failed, err: %v":                                                                231,
	"batch process by service templates failed, err: %v":                                                       192,
	"batch process count by service instances failed, err: %v":                                                 195,
	"batch recovery config items failed":                                                                       19,
	"batch recovery kv failed":                                                                                 43,
	"batch update app template binding's failed, err: %s":                                                      330,
	"batch update app template binding's failed, err: %v":                                                      335,
	"batch update of template permissions failed, err: %s":                                                     338,
	"batch upsert vault failed, err: %v":                                                                       234,
	"biz id is required":                                                                                       79,
	"bizID can not be 0":                                                                                       369,
	"biz_id is required":                                                                                       108,
	"build process operate task failed, err: %v":                                                               255,
	"business query failed, err: %v":                                                                           59,
	"calculate relative path failed, base: %s, dst: %s, err: %v":                                               489,
	"cc_process_id is required":                                                                                110,
	"check running config push tasks failed, err: %v":                                                          126,
	"clearing draft area failed, err: %v":                                                                      233,
	"client ids is empty":                                                                                      17,
	"commit spec's content is empty":                                                                           446,
	"commit transaction failed, err: %v":                                                                       208,
	"config instance not found, biz_id=%d, config_template_id=%d, cc_process_id=%d, module_inst_seq=%d": 150,
	"config item %s format error":               32,
	"config item %s json format error":          33,
	"config item %s kv type error":              30,
	"config item %s secret hidden error":        35,
	"config item %s secret type error, err: %v": 37,
	"config item %s value error":                38,
	"config item %s yaml format error":          34,
	"config payload is nil for task %s":         131,
	"config payload not found in task":          107,
	"config template %d version is not the latest, current: %d, latest: %d, please regenerate config": 130,
	"config template already has running push tasks, please wait for completion":                      127,
	"config template id is not valid for task %s":                                                     133,
	"config template id is required":                                                                  81,
	"config template version id is not latest":                                                        142,
	"config template version id is required":                                                          82,
	"config templates not found for ids: %s":                                                          92,
	"content id can not set":                                                                          453,
	"content signature should be lowercase":                                                           455,
	"count app %d's config items failed, err: %v":                                                     357,
	"count applications by environment failed":                                                        350,
	"count applications under projects failed":                                                        351,
	"count the number of app configs failed, err: %s":                                                 343,
	"count the number of kV files that have not been deleted failed, err: %v":                         237,
	"count the number of service configurations failed, err: %s":                                      74,
	"create app failed, err: %v":                                                                      355,
	"create batch failed, err: %v":                                                                    125,
	"create config template failed, err: %v":                                                          182,
	"create data failed, err: %v":                                                                     354,
	"create default template configuration space failed, err: %v":                                     188,
	"create default template set failed, err: %v":                                                     190,
	"create directory failed, err: %v":                                                                3,
	"create file failed, path: %s, err: %v":                                                           492,
	"create kv failed, err: %v":                                                                       225,
	"create parent directory failed, dir: %s, err: %v":                                                491,
	"create release failed there is a certificate expiration exists":                                  307,
	"create release failed there is a file conflict":                                                  306,
	"create run config generation or verification task failed, err: %v":                               148,
	"create sync cmdb task failed, err: %v":                                                           311,
	"create task batch failed, err: %v":                                                               252,
	"create template and revision failed, err: %v":                                                    181,
	"create template failed, err: %v":                                                                 183,
	"create template revision failed, err: %v":                                                        185,
	"create temporary directory failed, err: %v":                                                      4,
	"db operation failed":                                                                             398,
	"decompress file failed, exceeding the maximum file limit threshold of %d":                        13,
	"decompress the file. The size of file %s exceeds the maximum limit of %s":                        5,
	"decompression failed, err: %v":                                                                   6,
	"default_val %s is not a number type":                                                             485,
	"delete app failed, err: %v":                                                                      57,
	"delete app related resources failed, err: %v":                                                    56,
	"delete config template failed, err: %v":                                                          207,
	"delete one app template binding instance by app id failed, err: %s":                              155,
	"delete one app template variable failed, err: %s":                                                157,
	"delete process instance %d failed, err: %v":                                                      265,
	"delete template failed, err: %v":                                                                 204,
	"delete template from all sets failed, err: %v":                                                   206,
	"delete template from template sets failed":                                                       47,
	"delete template from template sets failed, err: %v":                                              333,
	"delete template revision failed, err: %v":                                                        205,
	"download template config failed, template id: %d, name: %s, path: %s, err: %v":                   152,
	"environment application count failed":                                                            349,
	"environment count failed":                                                                        360,
	"environment creation failed":                                                                     363,
	"environment deletion failed":                                                                     362,
	"environment does not exist":                                                                      218,
	"environment is nil":                                                                              361,
	"environment is protected, cannot be deleted":                                                     214,
	"environment list failed":                                                                         217,
	"environment name %s already exists":                                                              213,
	"environment query failed":                                                                        365,
	"environment update failed":                                                                       364,
	"expand ginclude failed, err: %v":                                                                 114,
	"fetch all module details failed, err: %v":                                                        176,
	"fetch all service template failed, err: %v":                                                      191,
	"find topo brief failed, err: %v":                                                                 173,
	"format error, please check the key: %s":                                                          31,
	"get 'kv_type' as a string \n\t\tfrom kv.Data failed, err: %v":                                    393,
	"get a list of expired certificates failed, err: %v":                                              227,
	"get absolute base path failed, baseDir: %s, err: %v":                                             487,
	"get absolute destination path failed, path: %s, err: %v":                                         488,
	"get all config templates failed, err: %v":                                                        86,
	"get app %d's template binding failed, err: %v":                                                   358,
	"get app fail, key: %s, err: %v":                                                                  223,
	"get app failed, err: %v":                                                                         54,
	"get app template bindings by template set ids, err: %s":                                          329,
	"get app template bindings by template set ids, err: %v":                                          334,
	"get batch failed, batch_id: %d, err: %v":                                                         116,
	"get biz object attributes failed, err: %v":                                                       197,
	"get business data failed, err: %v":                                                               312,
	"get common payload failed, err: %v":                                                              104,
	"get common payload from task failed, err: %v":                                                    320,
	"get config item failed, err: %v":                                                                 153,
	"get config template %d failed, err: %v":                                                          128,
	"get config template by ID failed, err: %v":                                                       198,
	"get config template by unique key failed, err: %v":                                               178,
	"get config template failed, err: %v":                                                             78,
	"get default template configuration space failed, err: %v":                                        187,
	"get default template set failed, err: %v":                                                        189,
	"get environment by name failed":                                                                  212,
	"get excluded hook failed, err: %s":                                                               220,
	"get excluded kv failed, err: %s":                                                                 236,
	"get key value failed, err: %v":                                                                   228,
	"get kv (%d) failed, err: %v":                                                                     222,
	"get latest template revision failed, err: %v":                                                    99,
	"get latest template revision for config template %d failed, err: %v":                             129,
	"get operate payload from task step failed, taskID: %s, err: %v":                                  325,
	"get permission to apply failed, err: %v":                                                         396,
	"get process failed, err: %v":                                                                     143,
	"get process instance by ID %d failed, err: %v":                                                   326,
	"get process instances by IDs failed, err: %v":                                                    246,
	"get process instances by process IDs failed, err: %v":                                            239,
	"get process instances failed, err: %v":                                                           95,
	"get processes by operate range failed, err: %v":                                                  84,
	"get processes failed, err: %v":                                                                   249,
	"get records greater than the latest released version failed, err: %v":                            163,
	"get reference template set under this app failed, err: %s":                                       167,
	"get source batch task data failed, err: %v":                                                      124,
	"get task batch %d failed, err: %v":                                                               316,
	"get task batch failed, err: %v":                                                                  135,
	"get task failed, err: %v":                                                                        105,
	"get template binding relationships through business and service IDs failed, err: %s":             166,
	"get template by ID failed, err: %v":                                                              203,
	"get template count failed, err: %v":                                                              389,
	"get template failed, err: %v":                                                                    97,
	"get template file failed, err: %v":                                                               309,
	"get template release failed, err: %v":                                                            385,
	"get template set count failed, err: %v":                                                          387,
	"get template set data failed, err: %s":                                                           331,
	"get template set failed, err: %s":                                                                340,
	"get template set failed, err: %v":                                                                180,
	"get the current number of service config items failed, err: %v":                                  12,
	"get the latest released version failed, err: %v":                                                 159,
	"get the package associated with the app failed, err: %v":                                         308,
	"get the published config failed, err: %v":                                                        160,
	"gray_percent key must be equal":                                                                  21,
	"gray_percent value must be a valid percentage (1-99)":                                            22,
	"grpc status with details failed, err: %v":                                                        397,
	"hook is nil":                 366,
	"hook name %s already exists": 219,
	"id can not be set":           434,
	"id is required":              0,
	"id should be set":            464,
	"id should not be set":        400,
	"if gray_percent groups exist, all groups must contain gray_percent label": 44,
	"invalid %s format: %v":            322,
	"invalid app id":                   458,
	"invalid argument":                 399,
	"invalid attachment biz id":        462,
	"invalid attachment project id":    463,
	"invalid base directory":           486,
	"invalid binding relationship":     145,
	"invalid biz id":                   435,
	"invalid biz_id":                   283,
	"invalid commit spec's content id": 445,
	"invalid config item id":           459,
	"invalid content signature, should be config's sha256 value": 454,
	"invalid data-type": 443,
	"invalid environment name, length should be greater than 0":                                                                              431,
	"invalid environment name, length should be less than or equal to 255":                                                                   432,
	"invalid environment name, only letters, numbers, underscores and hyphens are allowed,and it must start and end with a letter or number": 433,
	"invalid environment type":                460,
	"invalid file name":                       1,
	"invalid file path":                       490,
	"invalid memo, length should <= 200":      416,
	"invalid name %s, name cannot all be '.'": 425,
	"invalid name %s, only allows Chinese, English, numbers, underscore (_), hyphen (-), dot (.) and space": 426,
	"invalid name, length should <= 128":                                                 419,
	"invalid name, length should <= 64":                                                  424,
	"invalid name, length should >= 1":                                                   418,
	"invalid name, length should >= 9 and must start with prefix bk_bscp_ (ignore case)": 421,
	"invalid name: %s, only allows to include Chinese, English,numbers, underscore (_),hyphen (-), and must start and end with Chinese, English, or a number": 423,
	"invalid name: %s, only allows to include english、numbers、underscore (_), and must start with prefix bk_bscp_ (ignore case)":                              422,
	"invalid name: %s, only allows to include english、numbers、underscore (_)、hyphen (-), and must start and end with an english、numbers":                      420,
	"invalid namespace, length should <= 128":                                               428,
	"invalid namespace, length should >= 1":                                                 427,
	"invalid origin content signature, should be config's sha256 value":                     456,
	"invalid path %s, length should <= 1024":                                                405,
	"invalid path %s, length should >= 1":                                                   404,
	"invalid path %s, the path must start with '/'":                                         406,
	"invalid path %s, the pathcannot contain consecutive '/'":                               407,
	"invalid path, length should <= 256":                                                    409,
	"invalid path, length should >= 1":                                                      408,
	"invalid path,path does not conform to the win file path format specification":          410,
	"invalid publish_status: %s":                                                            292,
	"invalid reload file path, should <= 128":                                               412,
	"invalid spec, is nil":                                                                  436,
	"invalid username, length should <= 32":                                                 430,
	"invalid username, length should >= 1":                                                  429,
	"json format error, err: %v":                                                            27,
	"key should be set":                                                                     465,
	"keys is required":                                                                      42,
	"kv type does not match the data type defined in the application":                       224,
	"latest revision not found for template %d":                                             89,
	"list app template bindings by app ids failed, err: %s":                                 339,
	"list applications by environment ids failed":                                           352,
	"list apps by app ids failed, err: %s":                                                  342,
	"list config instances by template ID failed, err: %v":                                  171,
	"list config instances failed, err: %v":                                                 96,
	"list config item failed, err: %v":                                                      11,
	"list config templates by CC process ID failed, err: %v":                                240,
	"list config templates by CC template process ID failed, err: %v":                       241,
	"list config templates by ids failed, err: %v":                                          91,
	"list config templates failed, err: %v":                                                 90,
	"list distinct executors failed, err: %v":                                               314,
	"list failed tasks from task storage failed, err: %v":                                   261,
	"list filtered processes failed, err: %v":                                               94,
	"list kv failed, err: %v":                                                               230,
	"list latest revisions failed, err: %v":                                                 88,
	"list proc template failed, err: %v":                                                    193,
	"list process filter options (CC process IDs) failed, err: %v":                          259,
	"list process filter options (aliases) failed, err: %v":                                 260,
	"list process filter options (inner IP) failed, err: %v":                                266,
	"list process filter options (modules) failed, err: %v":                                 257,
	"list process filter options (service instances) failed, err: %v":                       258,
	"list process filter options (sets) failed, err: %v":                                    256,
	"list process instance failed, err: %v":                                                 196,
	"list processes by cc process IDs failed, err: %v":                                      200,
	"list processes by process template IDs failed, err: %v":                                201,
	"list processes by template process ids failed, err: %v":                                93,
	"list processes failed for process instance topo, err: %v":                              262,
	"list processes failed, err: %v":                                                        177,
	"list service instance failed, err: %v":                                                 194,
	"list task batch failed, err: %v":                                                       313,
	"list task failed, err: %v":                                                             118,
	"list tasks failed, err: %v":                                                            103,
	"list tasks from task storage failed for status %s, err: %v":                            321,
	"list tasks from task storage failed, err: %v":                                          317,
	"list tasks returned nil pagination":                                                    318,
	"list template config failed, err: %v":                                                  8,
	"list template revisions by ids failed, err: %v":                                        100,
	"list template revisions failed, err: %v":                                               71,
	"list template sets by template set ids failed, err: %s":                                168,
	"list template sets by template set ids failed, err: %v":                                64,
	"list template spaces failed, err: %v":                                                  66,
	"list templates by IDs failed, err: %v":                                                 172,
	"list templates by tuple failed, err: %v":                                               336,
	"list templates data failed, err: %s":                                                   345,
	"list templates failed, err: %v":                                                        15,
	"list templates of template set failed, err: %v":                                        69,
	"list templates revisions data failed, err: %s":                                         347,
	"lists the latest version by template ids failed, err: %s":                              337,
	"memo is required, can not be empty":                                                    415,
	"name should be set":                                                                    461,
	"no available space or packages":                                                        170,
	"no available topo nodes":                                                               174,
	"no executable config bindings in the operate range":                                    87,
	"no permission to approve":                                                              298,
	"no permission to approve this ticket":                                                  293,
	"no process instances found for process IDs %v":                                         251,
	"no process instances found for processes matching operate range":                       245,
	"no processes found for biz %d with provided operate range":                             85,
	"no processes found for biz %d with provided process IDs":                               250,
	"no tasks to create":                                                                    146,
	"no valid module IDs found":                                                             175,
	"no valid tasks found for batch %d":                                                     134,
	"non-gray_percent labels must be consistent across all gray_percent groups":             45,
	"not a KV type service":                                                                 229,
	"not legal JSON data":                                                                   26,
	"not support table config type for now":                                                 440,
	"obtain the number of configuration items":                                              165,
	"operate process step not found for taskID: %s":                                         324,
	"operate type is not supported: %v":                                                     243,
	"origin content signature should be lowercase":                                          457,
	"pass not allowed, current publish status is: %s":                                       299,
	"path cannot be empty":                                                                  209,
	"path cannot contain null character":                                                    210,
	"path contains invalid segment: %s":                                                     211,
	"payload not found in task":                                                             149,
	"please fill in the value of configuration item %s first":                               39,
	"process %d is not in the config template":                                              101,
	"process config view is not enabled for biz %d":                                         310,
	"process instance with ID %d does not exist":                                            327,
	"process instances not found for IDs %v":                                                247,
	"process list is required":                                                              83,
	"process not found for cc process id: %d":                                               98,
	"process not found for cc_process_id: %d":                                               112,
	"process not found for id %d":                                                           248,
	"process not found in processMap, processID=%d":                                         254,
	"process payload is nil for task %s":                                                    132,
	"project creation failed":                                                               373,
	"project does not exist":                                                                370,
	"project is nil":                                                                        372,
	"project is protected, cannot be deleted":                                               284,
	"project list failed":                                                                   286,
	"project query failed":                                                                  371,
	"project update failed":                                                                 374,
	"publish not allowed, current publish status is: %s":                                    300,
	"query failed tasks failed, err: %v":                                                    139,
	"query process by cc_process_id failed, err: %v":                                        111,
	"query process instance failed, err: %v":                                                113,
	"query_status operation is not supported":                                               244,
	"read file failed, err: %v":                                                             2,
	"reason can not empty":                                                                  297,
	"recover config item failed, err: %v":                                                   162,
	"recovery failed. A file with the same path exists and is not in a new state":           161,
	"regenerate task failed, err: %v":                                                       138,
	"rejected not allowed, current publish status is: %s":                                   296,
	"release %s is deprecated, can not be revoke":                                           291,
	"release %s is deprecated, can not be submited":                                         289,
	"release name %s already exists":                                                        294,
	"reload file path is not the absolute path":                                             413,
	"reload file path is required":                                                          411,
	"remove the template set bound to the app failed, err: %s":                              169,
	"render template failed, err: %v":                                                       115,
	"reset counts for retry failed, err: %v":                                                140,
	"reset task batch counts for retry failed, batchID: %d, err: %v":                        323,
	"resource name '%s' is prefixed with '%s' is reserved name, which is not allows to use": 417,
	"retrieve the referenced script failed, err: %s":                                        221,
	"retry failed task %s failed, err: %v":                                                  328,
	"retry failed task failed, err: %v":                                                     141,
	"revision not set":                                                                      403,
	"revision should be set":                                                                483,
	"revoked not allowed, current publish status is: %s":                                    295,
	"same template variable name %s already exists":                                         348,
	"save kv failed":                                                                        61,
	"sensitive data is not visible, unable to view actual content":                          25,
	"sensitive information cannot be exported":                                              16,
	"some processes not found for biz %d":                                                   144,
	"spec not set":                                                                          401,
	"spec should be set":                                                                    444,
	"task batch %d does not exist":                                                          136,
	"task is nil":                                                                           319,
	"task not found: %s":                                                                    106,
	"task storage is not initialized":                                                       315,
	"task storage not initialized":                                                          102,
	"template %d is not exist":                                                              383,
	"template data is empty":                                                                346,
	"template id in %v is not belong to template set id %d":                                 392,
	"template id in %v is not exist":                                                        378,
	"template not match template revision, template_id=%d, template_revision_id=%d":         151,
	"template release %d is not exist":                                                      384,
	"template revision id in %v is not exist":                                               380,
	"template set %d is not exist":                                                          386,
	"template set %s not found":                                                             68,
	"template set data is empty":                                                            344,
	"template set id in %v is not exist":                                                    382,
	"template space %s not found":                                                           67,
	"template space id in %v is not exist":                                                  377,
	"template space id should be set":                                                       484,
	"template variable %s type error":                                                       50,
	"template variable name must start with %s":                                             48,
	"template version %s in template file %s\n\t\t\t\thas been removed. Please import the set again": 72,
	"template_content is required": 109,
	"the certificate format is incorrect, only X.509 format is supported, err: %v":     41,
	"the config file %s already exists in this space and cannot be created again":      63,
	"the config item %s under this service already exists and cannot be created again": 154,
	"the data has not been deleted":                                                    158,
	"the default environment under the production space cannot be deleted":             215,
	"the key type for config item %s cannot be empty":                                  36,
	"the length of hook ids is %d, it must be within the range of [1,%d]":              23,
	"the length of template variable ids is %d, it must be within the range of [1,%d]": 49,
	"the password of configuration item %s is not complex enough, it must contain at least 3 types of the following: uppercase letters, lowercase letters, numbers and special characters": 40,
	"the same template name already exists under this %d business: %s":                                                                         179,
	"the specified type does not match the actual configuration":                                                                               55,
	"the success task count of batch %s does not match its total count (settled %s), still inconsistent after waiting %s, config push aborted": 121,
	"the template file %s in the template set\n\t\t\t\t%s has been removed. Please import the set again":                                       70,
	"the total number of app %d's config items(including template and non-template)exceeded the limit %d":                                      359,
	"the total number of app %s config items(including template and non-template)exceeded the limit %d":                                        76,
	"the total number of config items exceeded the limit %d":                                                                                   238,
	"the total number of config items(including template and non-template)\n\t\t\texceeded the limit %d":                                       164,
	"the total number of template set %d's templates exceeded the limit %d":                                                                    375,
	"the total number of template set %s templates exceeded the limit %d":                                                                      341,
	"the type of config item %s is incorrect":                                                                                                  232,
	"the version number %s in the template file %s is not the\n\t\tlatest version. Please import the set again":                                73,
	"there are duplicate keys %s": 235,
	"there are still active resources in the environments under this project, cannot be deleted": 285,
	"there are still app under the environments, please delete the app first":                    216,
	"there are template sets under the template space, need to delete them first":                388,
	"there are templates under the template space, need to delete them first":                    390,
	"there is a release in publishing currently":                                                 290,
	"there is no template file under this template set":                                          332,
	"this ticket has been approved, no further processing is required":                           305,
	"this ticket has been finished, no further processing is required":                           302,
	"this ticket has been rejected, no further processing is required":                           304,
	"this ticket has been revoked, no further processing is required":                            301,
	"undefined task action":                                              46,
	"unknown config type: %s":                                            438,
	"unknown operation type: %s":                                         137,
	"unsupported app reload type: %s":                                    442,
	"unsupported config task mode: %v":                                   147,
	"unsupported config type: %s":                                        441,
	"unsupported file charset: %s":                                       451,
	"unsupported file format: %s":                                        449,
	"unsupported file mode: %s":                                          450,
	"unsupported highlight style: %s":                                    452,
	"unsupported managed status for delete: %s":                          263,
	"unsupported process state for delete: status=%s managedStatus=%s":   264,
	"unsupported variable type: %s":                                      51,
	"update app failed, err: %s":                                         356,
	"update app template binding failed, err: %v":                        65,
	"update config template failed, err: %v":                             199,
	"update kv failed, err: %v":                                          226,
	"update process instance status failed, err: %v":                     253,
	"update template failed, err: %v":                                    202,
	"upload completed":                                                   9,
	"upload completed, %d failed":                                        10,
	"upload failed, please make sure the file size does not exceed %s":   14,
	"upload file failed, err: %v":                                        7,
	"validate page parameters failed, err: %v":                           77,
	"validate template releases exist failed, err: %v":                   379,
	"validate template sets exist failed, err: %v":                       381,
	"validate templates exist failed, err: %v":                           376,
	"validate templates in a template set failed, err: %v":               391,
	"value type assertion failed, err: %v":                               394,
	"verify Unix file paths failed, path: %s, err: %v":                   448,
	"verify Windows file paths failed, path: %s, err: %v":                447,
	"version number %s already exists. Please change it and try again.":  184,
	"waiting for tasks of batch %s to settle is canceled, err: %v":       120,
	"when ProcessInstanceId is specified, only one ProcessId is allowed": 242,
	"write file failed, path: %s, err: %v":                               493,
	"yaml format error, err: %v":                                         28,
}

var enIndex = []uint32{ // 496 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000f, 0x00000021, 0x0000003e,
	0x00000062, 0x00000090, 0x000000df, 0x00000100,
	0x0000011f, 0x00000147, 0x00000158, 0x00000177,
	0x0000019b, 0x000001dd, 0x00000229, 0x0000026d,
	0x0000028f, 0x000002b8, 0x000002cc, 0x000002ed,
	0x00000310, 0x0000032b, 0x0000034a, 0x0000037f,
	0x000003c9, 0x000003dd, 0x0000041a, 0x0000042e,
	0x0000044c, 0x0000046a, 0x00000483, 0x000004a3,
	// Entry 20 - 3F
	0x000004cd, 0x000004ec, 0x00000510, 0x00000534,
	0x0000055a, 0x0000058d, 0x000005bd, 0x000005db,
	0x00000616, 0x000006ce, 0x0000071e, 0x0000072f,
	0x00000748, 0x00000791, 0x000007db, 0x000007f1,
	0x0000081b, 0x00000848, 0x0000089f, 0x000008c2,
	0x000008e3, 0x00000901, 0x00000920, 0x0000093b,
	0x00000976, 0x000009a6, 0x000009c4, 0x000009d8,
	0x000009fa, 0x00000a1d, 0x00000a2c, 0x00000a59,
	// Entry 40 - 5F
	0x00000aa8, 0x00000ae2, 0x00000b11, 0x00000b39,
	0x00000b58, 0x00000b75, 0x00000ba7, 0x00000c0b,
	0x00000c36, 0x00000c96, 0x00000d03, 0x00000d41,
	0x00000d5c, 0x00000dc4, 0x00000df0, 0x00000e17,
	0x00000e2a, 0x00000e59, 0x00000e78, 0x00000e9f,
	0x00000eb8, 0x00000eea, 0x00000f27, 0x00000f53,
	0x00000f86, 0x00000faf, 0x00000fdc, 0x00001005,
	0x00001035, 0x0000105f, 0x00001099, 0x000010c4,
	// Entry 60 - 7F
	0x000010ed, 0x00001116, 0x00001136, 0x00001161,
	0x00001191, 0x000011c3, 0x000011ef, 0x0000120c,
	0x0000122a, 0x00001250, 0x0000126c, 0x00001282,
	0x000012a3, 0x000012b6, 0x000012d3, 0x000012ed,
	0x0000131f, 0x0000134a, 0x00001374, 0x00001397,
	0x000013ba, 0x000013e8, 0x00001413, 0x00001430,
	0x00001467, 0x000014aa, 0x0000153c, 0x000015ab,
	0x0000160d, 0x0000163b, 0x0000165b, 0x0000168e,
	// Entry 80 - 9F
	0x000016d9, 0x00001706, 0x00001750, 0x000017b9,
	0x000017de, 0x00001804, 0x00001833, 0x00001858,
	0x0000187a, 0x0000189a, 0x000018b8, 0x000018db,
	0x00001901, 0x0000192b, 0x00001950, 0x00001979,
	0x00001998, 0x000019bf, 0x000019dc, 0x000019ef,
	0x00001a13, 0x00001a58, 0x00001a72, 0x00001ae0,
	0x00001b34, 0x00001b8e, 0x00001bb1, 0x00001c05,
	0x00001c4b, 0x00001c74, 0x00001ca8, 0x00001cc6,
	// Entry A0 - BF
	0x00001cf9, 0x00001d25, 0x00001d71, 0x00001d98,
	0x00001de0, 0x00001e42, 0x00001e6b, 0x00001ec2,
	0x00001eff, 0x00001f39, 0x00001f75, 0x00001f94,
	0x00001fcc, 0x00001ff5, 0x00002018, 0x00002030,
	0x0000204a, 0x00002076, 0x00002098, 0x000020cd,
	0x00002114, 0x00002138, 0x00002168, 0x00002192,
	0x000021b5, 0x000021fa, 0x00002226, 0x0000225e,
	0x0000229a, 0x000022d9, 0x00002305, 0x00002334,
	// Entry C0 - DF
	0x00002362, 0x00002398, 0x000023be, 0x000023e7,
	0x00002423, 0x0000244c, 0x00002479, 0x000024a6,
	0x000024d0, 0x00002504, 0x0000253e, 0x00002561,
	0x00002587, 0x000025aa, 0x000025d6, 0x00002607,
	0x00002631, 0x00002657, 0x0000266c, 0x0000268f,
	0x000026b4, 0x000026d3, 0x000026f9, 0x00002725,
	0x0000276a, 0x000027b2, 0x000027ca, 0x000027e5,
	0x00002804, 0x00002829, 0x0000285b, 0x0000287d,
	// Entry E0 - FF
	0x000028a2, 0x000028e2, 0x000028ff, 0x0000291c,
	0x00002952, 0x00002973, 0x00002989, 0x000029a4,
	0x000029d1, 0x000029fc, 0x00002a23, 0x00002a49,
	0x00002a68, 0x00002a8b, 0x00002ad6, 0x00002b10,
	0x00002b48, 0x00002b82, 0x00002bc5, 0x00002c08,
	0x00002c2d, 0x00002c55, 0x00002c95, 0x00002cc5,
	0x00002cef, 0x00002d0e, 0x00002d2f, 0x00002d6a,
	0x00002d9b, 0x00002dc0, 0x00002df2, 0x00002e23,
	// Entry 100 - 11F
	0x00002e51, 0x00002e87, 0x00002ec0, 0x00002f03,
	0x00002f43, 0x00002f7c, 0x00002fb3, 0x00002fef,
	0x0000301c, 0x00003063, 0x00003094, 0x000030ce,
	0x000030d6, 0x000030e7, 0x000030f0, 0x000030fb,
	0x00003104, 0x0000310e, 0x00003119, 0x0000312c,
	0x0000313f, 0x00003147, 0x00003151, 0x00003162,
	0x00003169, 0x00003171, 0x00003179, 0x00003182,
	0x00003191, 0x000031b9, 0x00003214, 0x00003228,
	// Entry 120 - 13F
	0x0000323b, 0x0000324c, 0x0000327d, 0x000032a8,
	0x000032d7, 0x000032f5, 0x0000331a, 0x0000333c,
	0x00003372, 0x000033a9, 0x000033be, 0x000033d7,
	0x0000340a, 0x00003440, 0x00003480, 0x000034c1,
	0x000034f9, 0x0000353a, 0x0000357b, 0x000035aa,
	0x000035e9, 0x00003624, 0x00003649, 0x0000367a,
	0x000036a3, 0x000036c8, 0x000036eb, 0x00003716,
	0x00003736, 0x0000375e, 0x0000378e, 0x000037b1,
	// Entry 140 - 15F
	0x000037bd, 0x000037ed, 0x0000382e, 0x0000384a,
	0x0000388f, 0x000038c0, 0x00003905, 0x00003939,
	0x00003967, 0x00003992, 0x000039cc, 0x00003a03,
	0x00003a2c, 0x00003a5e, 0x00003a94, 0x00003ace,
	0x00003b05, 0x00003b30, 0x00003b6c, 0x00003ba4,
	0x00003bdd, 0x00003c01, 0x00003c4b, 0x00003c73,
	0x00003ca6, 0x00003cc1, 0x00003ce8, 0x00003cff,
	0x00003d30, 0x00003d61, 0x00003d86, 0x00003daf,
	// Entry 160 - 17F
	0x00003dd8, 0x00003e04, 0x00003e0f, 0x00003e2e,
	0x00003e4c, 0x00003e6a, 0x00003e9c, 0x00003ed0,
	0x00003f3a, 0x00003f53, 0x00003f66, 0x00003f82,
	0x00003f9e, 0x00003fb8, 0x00003fd1, 0x00003fdd,
	0x00003fed, 0x00004000, 0x00004013, 0x0000402a,
	0x0000403f, 0x0000404e, 0x00004066, 0x0000407c,
	0x000040c8, 0x000040f4, 0x0000411c, 0x0000413e,
	0x00004172, 0x0000419d, 0x000041cd, 0x000041f3,
	// Entry 180 - 19F
	0x0000420f, 0x00004233, 0x0000425b, 0x0000427b,
	0x000042a5, 0x000042f1, 0x00004317, 0x0000435f,
	0x00004397, 0x000043d3, 0x00004410, 0x00004438,
	0x00004449, 0x00004474, 0x000044a0, 0x000044b4,
	0x000044c5, 0x000044da, 0x000044e7, 0x000044fa,
	0x0000450b, 0x00004532, 0x0000455c, 0x0000458d,
	0x000045c8, 0x000045e9, 0x0000460c, 0x00004659,
	0x00004676, 0x0000469e, 0x000046c8, 0x00004704,
	// Entry 1A0 - 1BF
	0x00004727, 0x0000474a, 0x000047a6, 0x000047c7,
	0x000047ea, 0x00004878, 0x000048cb, 0x0000494d,
	0x000049e8, 0x00004a0a, 0x00004a35, 0x00004a9e,
	0x00004ac4, 0x00004aec, 0x00004b11, 0x00004b37,
	0x00004b71, 0x00004bb6, 0x00004c3d, 0x00004c4f,
	0x00004c5e, 0x00004c73, 0x00004c83, 0x00004c9e,
	0x00004cbc, 0x00004ce2, 0x00004d01, 0x00004d24,
	0x00004d36, 0x00004d49, 0x00004d6a, 0x00004d89,
	// Entry 1C0 - 1DF
	0x00004dc3, 0x00004dfa, 0x00004e19, 0x00004e36,
	0x00004e56, 0x00004e79, 0x00004e90, 0x00004ecb,
	0x00004ef1, 0x00004f33, 0x00004f60, 0x00004f6f,
	0x00004f86, 0x00004f9f, 0x00004fb2, 0x00004fcc,
	0x00004fea, 0x00004ffb, 0x0000500d, 0x00005018,
	0x00005020, 0x00005026, 0x0000502b, 0x00005033,
	0x0000503a, 0x0000503f, 0x00005048, 0x00005053,
	0x00005061, 0x00005070, 0x0000507c, 0x00005086,
	// Entry 1E0 - 1FF
	0x0000509a, 0x000050aa, 0x000050b9, 0x000050d2,
	0x000050e9, 0x00005109, 0x00005130, 0x00005147,
	0x00005181, 0x000051bf, 0x00005203, 0x00005215,
	0x0000524c, 0x00005278, 0x000052a3, 0x000052c6,
} // Size: 2008 bytes

const enData string = "" + // Size: 21190 bytes
	"\x02id is required\x02invalid file name\x02read file failed, err: %[1]v" +
	"\x02create directory failed, err: %[1]v\x02create temporary directory fa" +
	"iled, err: %[1]v\x02decompress the file. The size of file %[1]s exceeds " +
	"the maximum limit of %[2]s\x02decompression failed, err: %[1]v\x02upload" +
	" file failed, err: %[1]v\x02list template config failed, err: %[1]v\x02u" +
	"pload completed\x02upload completed, %[1]d failed\x02list config item fa" +
	"iled, err: %[1]v\x02get the current number of service config items faile" +
	"d, err: %[1]v\x02decompress file failed, exceeding the maximum file limi" +
	"t threshold of %[1]d\x02upload failed, please make sure the file size do" +
	"es not exceed %[1]s\x02list templates failed, err: %[1]v\x02sensitive in" +
	"formation cannot be exported\x02client ids is empty\x02batch delete conf" +
	"ig items failed\x02batch recovery config items failed\x02batch delete gr" +
	"oups failed\x02gray_percent key must be equal\x02gray_percent value must" +
	" be a valid percentage (1-99)\x02the length of hook ids is %[1]d, it mus" +
	"t be within the range of [1,%[2]d]\x02batch delete failed\x02sensitive d" +
	"ata is not visible, unable to view actual content\x02not legal JSON data" +
	"\x02json format error, err: %[1]v\x02yaml format error, err: %[1]v\x02%[" +
	"1]s type not supported\x02config item %[1]s kv type error\x02format erro" +
	"r, please check the key: %[1]s\x02config item %[1]s format error\x02conf" +
	"ig item %[1]s json format error\x02config item %[1]s yaml format error" +
	"\x02config item %[1]s secret hidden error\x02the key type for config ite" +
	"m %[1]s cannot be empty\x02config item %[1]s secret type error, err: %[2" +
	"]v\x02config item %[1]s value error\x02please fill in the value of confi" +
	"guration item %[1]s first\x02the password of configuration item %[1]s is" +
	" not complex enough, it must contain at least 3 types of the following: " +
	"uppercase letters, lowercase letters, numbers and special characters\x02" +
	"the certificate format is incorrect, only X.509 format is supported, err" +
	": %[1]v\x02keys is required\x02batch recovery kv failed\x02if gray_perce" +
	"nt groups exist, all groups must contain gray_percent label\x02non-gray_" +
	"percent labels must be consistent across all gray_percent groups\x02unde" +
	"fined task action\x02delete template from template sets failed\x02templa" +
	"te variable name must start with %[1]s\x02the length of template variabl" +
	"e ids is %[1]d, it must be within the range of [1,%[2]d]\x02template var" +
	"iable %[1]s type error\x02unsupported variable type: %[1]s\x02app name %" +
	"[1]s already exists\x02app alias %[1]s already exists\x02get app failed," +
	" err: %[1]v\x02the specified type does not match the actual configuratio" +
	"n\x02delete app related resources failed, err: %[1]v\x02delete app faile" +
	"d, err: %[1]v\x02app %[1]d not found\x02business query failed, err: %[1]" +
	"v\x02app related biz %[1]d is not exist\x02save kv failed\x02batch creat" +
	"e of KV config failed, err: %[1]v\x02the config file %[1]s already exist" +
	"s in this space and cannot be created again\x02list template sets by tem" +
	"plate set ids failed, err: %[1]v\x02update app template binding failed, " +
	"err: %[1]v\x02list template spaces failed, err: %[1]v\x02template space " +
	"%[1]s not found\x02template set %[1]s not found\x02list templates of tem" +
	"plate set failed, err: %[1]v\x02the template file %[1]s in the template " +
	"set\x0a\x09\x09\x09\x09%[2]s has been removed. Please import the set aga" +
	"in\x02list template revisions failed, err: %[1]v\x02template version %[1" +
	"]s in template file %[2]s\x0a\x09\x09\x09\x09has been removed. Please im" +
	"port the set again\x02the version number %[1]s in the template file %[2]" +
	"s is not the\x0a\x09\x09latest version. Please import the set again\x02c" +
	"ount the number of service configurations failed, err: %[1]s\x02app %[1]" +
	"s is not file type\x02the total number of app %[1]s config items(includi" +
	"ng template and non-template)exceeded the limit %[2]d\x02validate page p" +
	"arameters failed, err: %[1]v\x02get config template failed, err: %[1]v" +
	"\x02biz id is required\x02at least one config template group is required" +
	"\x02config template id is required\x02config template version id is requ" +
	"ired\x02process list is required\x02get processes by operate range faile" +
	"d, err: %[1]v\x02no processes found for biz %[1]d with provided operate " +
	"range\x02get all config templates failed, err: %[1]v\x02no executable co" +
	"nfig bindings in the operate range\x02list latest revisions failed, err:" +
	" %[1]v\x02latest revision not found for template %[1]d\x02list config te" +
	"mplates failed, err: %[1]v\x02list config templates by ids failed, err: " +
	"%[1]v\x02config templates not found for ids: %[1]s\x02list processes by " +
	"template process ids failed, err: %[1]v\x02list filtered processes faile" +
	"d, err: %[1]v\x02get process instances failed, err: %[1]v\x02list config" +
	" instances failed, err: %[1]v\x02get template failed, err: %[1]v\x02proc" +
	"ess not found for cc process id: %[1]d\x02get latest template revision f" +
	"ailed, err: %[1]v\x02list template revisions by ids failed, err: %[1]v" +
	"\x02process %[1]d is not in the config template\x02task storage not init" +
	"ialized\x02list tasks failed, err: %[1]v\x02get common payload failed, e" +
	"rr: %[1]v\x02get task failed, err: %[1]v\x02task not found: %[1]s\x02con" +
	"fig payload not found in task\x02biz_id is required\x02template_content " +
	"is required\x02cc_process_id is required\x02query process by cc_process_" +
	"id failed, err: %[1]v\x02process not found for cc_process_id: %[1]d\x02q" +
	"uery process instance failed, err: %[1]v\x02expand ginclude failed, err:" +
	" %[1]v\x02render template failed, err: %[1]v\x02get batch failed, batch_" +
	"id: %[1]d, err: %[2]v\x02batch %[1]d is not a config generate batch\x02l" +
	"ist task failed, err: %[1]v\x02batch %[1]s total count is 0, there is no" +
	" task to push\x02waiting for tasks of batch %[1]s to settle is canceled," +
	" err: %[2]v\x02the success task count of batch %[1]s does not match its " +
	"total count (settled %[2]s), still inconsistent after waiting %[3]s, con" +
	"fig push aborted\x02batch %[1]s is still running (completed %[2]s), plea" +
	"se wait for the config generation to finish before pushing\x02batch %[1]" +
	"s has %[2]s failed task(s) (success %[3]s), please regenerate the config" +
	" before pushing\x02get source batch task data failed, err: %[1]v\x02crea" +
	"te batch failed, err: %[1]v\x02check running config push tasks failed, e" +
	"rr: %[1]v\x02config template already has running push tasks, please wait" +
	" for completion\x02get config template %[1]d failed, err: %[2]v\x02get l" +
	"atest template revision for config template %[1]d failed, err: %[2]v\x02" +
	"config template %[1]d version is not the latest, current: %[2]d, latest:" +
	" %[3]d, please regenerate config\x02config payload is nil for task %[1]s" +
	"\x02process payload is nil for task %[1]s\x02config template id is not v" +
	"alid for task %[1]s\x02no valid tasks found for batch %[1]d\x02get task " +
	"batch failed, err: %[1]v\x02task batch %[1]d does not exist\x02unknown o" +
	"peration type: %[1]s\x02regenerate task failed, err: %[1]v\x02query fail" +
	"ed tasks failed, err: %[1]v\x02reset counts for retry failed, err: %[1]v" +
	"\x02retry failed task failed, err: %[1]v\x02config template version id i" +
	"s not latest\x02get process failed, err: %[1]v\x02some processes not fou" +
	"nd for biz %[1]d\x02invalid binding relationship\x02no tasks to create" +
	"\x02unsupported config task mode: %[1]v\x02create run config generation " +
	"or verification task failed, err: %[1]v\x02payload not found in task\x02" +
	"config instance not found, biz_id=%[1]d, config_template_id=%[2]d, cc_pr" +
	"ocess_id=%[3]d, module_inst_seq=%[4]d\x02template not match template rev" +
	"ision, template_id=%[1]d, template_revision_id=%[2]d\x02download templat" +
	"e config failed, template id: %[1]d, name: %[2]s, path: %[3]s, err: %[4]" +
	"v\x02get config item failed, err: %[1]v\x02the config item %[1]s under t" +
	"his service already exists and cannot be created again\x02delete one app" +
	" template binding instance by app id failed, err: %[1]s\x02batch create " +
	"contents failed, err: %[1]s\x02delete one app template variable failed, " +
	"err: %[1]s\x02the data has not been deleted\x02get the latest released v" +
	"ersion failed, err: %[1]v\x02get the published config failed, err: %[1]v" +
	"\x02recovery failed. A file with the same path exists and is not in a ne" +
	"w state\x02recover config item failed, err: %[1]v\x02get records greater" +
	" than the latest released version failed, err: %[1]v\x02the total number" +
	" of config items(including template and non-template)\x0a\x09\x09\x09exc" +
	"eeded the limit %[1]d\x02obtain the number of configuration items\x02get" +
	" template binding relationships through business and service IDs failed," +
	" err: %[1]s\x02get reference template set under this app failed, err: %[" +
	"1]s\x02list template sets by template set ids failed, err: %[1]s\x02remo" +
	"ve the template set bound to the app failed, err: %[1]s\x02no available " +
	"space or packages\x02list config instances by template ID failed, err: %" +
	"[1]v\x02list templates by IDs failed, err: %[1]v\x02find topo brief fail" +
	"ed, err: %[1]v\x02no available topo nodes\x02no valid module IDs found" +
	"\x02fetch all module details failed, err: %[1]v\x02list processes failed" +
	", err: %[1]v\x02get config template by unique key failed, err: %[1]v\x02" +
	"the same template name already exists under this %[1]d business: %[2]s" +
	"\x02get template set failed, err: %[1]v\x02create template and revision " +
	"failed, err: %[1]v\x02create config template failed, err: %[1]v\x02creat" +
	"e template failed, err: %[1]v\x02version number %[1]s already exists. Pl" +
	"ease change it and try again.\x02create template revision failed, err: %" +
	"[1]v\x02batch add templates to template sets failed, err: %[1]s\x02get d" +
	"efault template configuration space failed, err: %[1]v\x02create default" +
	" template configuration space failed, err: %[1]v\x02get default template" +
	" set failed, err: %[1]v\x02create default template set failed, err: %[1]" +
	"v\x02fetch all service template failed, err: %[1]v\x02batch process by s" +
	"ervice templates failed, err: %[1]v\x02list proc template failed, err: %" +
	"[1]v\x02list service instance failed, err: %[1]v\x02batch process count " +
	"by service instances failed, err: %[1]v\x02list process instance failed," +
	" err: %[1]v\x02get biz object attributes failed, err: %[1]v\x02get confi" +
	"g template by ID failed, err: %[1]v\x02update config template failed, er" +
	"r: %[1]v\x02list processes by cc process IDs failed, err: %[1]v\x02list " +
	"processes by process template IDs failed, err: %[1]v\x02update template " +
	"failed, err: %[1]v\x02get template by ID failed, err: %[1]v\x02delete te" +
	"mplate failed, err: %[1]v\x02delete template revision failed, err: %[1]v" +
	"\x02delete template from all sets failed, err: %[1]v\x02delete config te" +
	"mplate failed, err: %[1]v\x02commit transaction failed, err: %[1]v\x02pa" +
	"th cannot be empty\x02path cannot contain null character\x02path contain" +
	"s invalid segment: %[1]s\x02get environment by name failed\x02environmen" +
	"t name %[1]s already exists\x02environment is protected, cannot be delet" +
	"ed\x02the default environment under the production space cannot be delet" +
	"ed\x02there are still app under the environments, please delete the app " +
	"first\x02environment list failed\x02environment does not exist\x02hook n" +
	"ame %[1]s already exists\x02get excluded hook failed, err: %[1]s\x02retr" +
	"ieve the referenced script failed, err: %[1]s\x02get kv (%[1]d) failed, " +
	"err: %[2]v\x02get app fail, key: %[1]s, err: %[2]v\x02kv type does not m" +
	"atch the data type defined in the application\x02create kv failed, err: " +
	"%[1]v\x02update kv failed, err: %[1]v\x02get a list of expired certifica" +
	"tes failed, err: %[1]v\x02get key value failed, err: %[1]v\x02not a KV t" +
	"ype service\x02list kv failed, err: %[1]v\x02batch import of KV config f" +
	"ailed, err: %[1]v\x02the type of config item %[1]s is incorrect\x02clear" +
	"ing draft area failed, err: %[1]v\x02batch upsert vault failed, err: %[1" +
	"]v\x02there are duplicate keys %[1]s\x02get excluded kv failed, err: %[1" +
	"]s\x02count the number of kV files that have not been deleted failed, er" +
	"r: %[1]v\x02the total number of config items exceeded the limit %[1]d" +
	"\x02get process instances by process IDs failed, err: %[1]v\x02list conf" +
	"ig templates by CC process ID failed, err: %[1]v\x02list config template" +
	"s by CC template process ID failed, err: %[1]v\x02when ProcessInstanceId" +
	" is specified, only one ProcessId is allowed\x02operate type is not supp" +
	"orted: %[1]v\x02query_status operation is not supported\x02no process in" +
	"stances found for processes matching operate range\x02get process instan" +
	"ces by IDs failed, err: %[1]v\x02process instances not found for IDs %[1" +
	"]v\x02process not found for id %[1]d\x02get processes failed, err: %[1]v" +
	"\x02no processes found for biz %[1]d with provided process IDs\x02no pro" +
	"cess instances found for process IDs %[1]v\x02create task batch failed, " +
	"err: %[1]v\x02update process instance status failed, err: %[1]v\x02proce" +
	"ss not found in processMap, processID=%[1]d\x02build process operate tas" +
	"k failed, err: %[1]v\x02list process filter options (sets) failed, err: " +
	"%[1]v\x02list process filter options (modules) failed, err: %[1]v\x02lis" +
	"t process filter options (service instances) failed, err: %[1]v\x02list " +
	"process filter options (CC process IDs) failed, err: %[1]v\x02list proce" +
	"ss filter options (aliases) failed, err: %[1]v\x02list failed tasks from" +
	" task storage failed, err: %[1]v\x02list processes failed for process in" +
	"stance topo, err: %[1]v\x02unsupported managed status for delete: %[1]s" +
	"\x02unsupported process state for delete: status=%[1]s managedStatus=%[2" +
	"]s\x02delete process instance %[1]d failed, err: %[2]v\x02list process f" +
	"ilter options (inner IP) failed, err: %[1]v\x02Running\x02PartiallyRunni" +
	"ng\x02Starting\x02Restarting\x02Stopping\x02Reloading\x02NotRunning\x02S" +
	"tartingManagement\x02StoppingManagement\x02Managed\x02Unmanaged\x02Parti" +
	"allyManaged\x02Normal\x02Deleted\x02Updated\x02Abnormal\x02invalid biz_i" +
	"d\x02project is protected, cannot be deleted\x02there are still active r" +
	"esources in the environments under this project, cannot be deleted\x02pr" +
	"oject list failed\x02app does not exist\x02app query failed\x02release %" +
	"[1]s is deprecated, can not be submited\x02there is a release in publish" +
	"ing currently\x02release %[1]s is deprecated, can not be revoke\x02inval" +
	"id publish_status: %[1]s\x02no permission to approve this ticket\x02rele" +
	"ase name %[1]s already exists\x02revoked not allowed, current publish st" +
	"atus is: %[1]s\x02rejected not allowed, current publish status is: %[1]s" +
	"\x02reason can not empty\x02no permission to approve\x02pass not allowed" +
	", current publish status is: %[1]s\x02publish not allowed, current publi" +
	"sh status is: %[1]s\x02this ticket has been revoked, no further processi" +
	"ng is required\x02this ticket has been finished, no further processing i" +
	"s required\x02approval has been revoked, invalid tikcet status: %[1]s" +
	"\x02this ticket has been rejected, no further processing is required\x02" +
	"this ticket has been approved, no further processing is required\x02crea" +
	"te release failed there is a file conflict\x02create release failed ther" +
	"e is a certificate expiration exists\x02get the package associated with " +
	"the app failed, err: %[1]v\x02get template file failed, err: %[1]v\x02pr" +
	"ocess config view is not enabled for biz %[1]d\x02create sync cmdb task " +
	"failed, err: %[1]v\x02get business data failed, err: %[1]v\x02list task " +
	"batch failed, err: %[1]v\x02list distinct executors failed, err: %[1]v" +
	"\x02task storage is not initialized\x02get task batch %[1]d failed, err:" +
	" %[2]v\x02list tasks from task storage failed, err: %[1]v\x02list tasks " +
	"returned nil pagination\x02task is nil\x02get common payload from task f" +
	"ailed, err: %[1]v\x02list tasks from task storage failed for status %[1]" +
	"s, err: %[2]v\x02invalid %[1]s format: %[2]v\x02reset task batch counts " +
	"for retry failed, batchID: %[1]d, err: %[2]v\x02operate process step not" +
	" found for taskID: %[1]s\x02get operate payload from task step failed, t" +
	"askID: %[1]s, err: %[2]v\x02get process instance by ID %[1]d failed, err" +
	": %[2]v\x02process instance with ID %[1]d does not exist\x02retry failed" +
	" task %[1]s failed, err: %[2]v\x02get app template bindings by template " +
	"set ids, err: %[1]s\x02batch update app template binding's failed, err: " +
	"%[1]s\x02get template set data failed, err: %[1]s\x02there is no templat" +
	"e file under this template set\x02delete template from template sets fai" +
	"led, err: %[1]v\x02get app template bindings by template set ids, err: %" +
	"[1]v\x02batch update app template binding's failed, err: %[1]v\x02list t" +
	"emplates by tuple failed, err: %[1]v\x02lists the latest version by temp" +
	"late ids failed, err: %[1]s\x02batch update of template permissions fail" +
	"ed, err: %[1]s\x02list app template bindings by app ids failed, err: %[1" +
	"]s\x02get template set failed, err: %[1]s\x02the total number of templat" +
	"e set %[1]s templates exceeded the limit %[2]d\x02list apps by app ids f" +
	"ailed, err: %[1]s\x02count the number of app configs failed, err: %[1]s" +
	"\x02template set data is empty\x02list templates data failed, err: %[1]s" +
	"\x02template data is empty\x02list templates revisions data failed, err:" +
	" %[1]s\x02same template variable name %[1]s already exists\x02environmen" +
	"t application count failed\x02count applications by environment failed" +
	"\x02count applications under projects failed\x02list applications by env" +
	"ironment ids failed\x02app is nil\x02create data failed, err: %[1]v\x02c" +
	"reate app failed, err: %[1]v\x02update app failed, err: %[1]s\x02count a" +
	"pp %[1]d's config items failed, err: %[2]v\x02get app %[1]d's template b" +
	"inding failed, err: %[2]v\x02the total number of app %[1]d's config item" +
	"s(including template and non-template)exceeded the limit %[2]d\x02enviro" +
	"nment count failed\x02environment is nil\x02environment deletion failed" +
	"\x02environment creation failed\x02environment update failed\x02environm" +
	"ent query failed\x02hook is nil\x02Unnamed Version\x02appID can not be 0" +
	"\x02bizID can not be 0\x02project does not exist\x02project query failed" +
	"\x02project is nil\x02project creation failed\x02project update failed" +
	"\x02the total number of template set %[1]d's templates exceeded the limi" +
	"t %[2]d\x02validate templates exist failed, err: %[1]v\x02template space" +
	" id in %[1]v is not exist\x02template id in %[1]v is not exist\x02valida" +
	"te template releases exist failed, err: %[1]v\x02template revision id in" +
	" %[1]v is not exist\x02validate template sets exist failed, err: %[1]v" +
	"\x02template set id in %[1]v is not exist\x02template %[1]d is not exist" +
	"\x02template release %[1]d is not exist\x02get template release failed, " +
	"err: %[1]v\x02template set %[1]d is not exist\x02get template set count " +
	"failed, err: %[1]v\x02there are template sets under the template space, " +
	"need to delete them first\x02get template count failed, err: %[1]v\x02th" +
	"ere are templates under the template space, need to delete them first" +
	"\x02validate templates in a template set failed, err: %[1]v\x02template " +
	"id in %[1]v is not belong to template set id %[2]d\x02get 'kv_type' as a" +
	" string \x0a\x09\x09from kv.Data failed, err: %[1]v\x02value type assert" +
	"ion failed, err: %[1]v\x02authorize failed\x02get permission to apply fa" +
	"iled, err: %[1]v\x02grpc status with details failed, err: %[1]v\x02db op" +
	"eration failed\x02invalid argument\x02id should not be set\x02spec not s" +
	"et\x02attachment not set\x02revision not set\x02invalid path %[1]s, leng" +
	"th should >= 1\x02invalid path %[1]s, length should <= 1024\x02invalid p" +
	"ath %[1]s, the path must start with '/'\x02invalid path %[1]s, the pathc" +
	"annot contain consecutive '/'\x02invalid path, length should >= 1\x02inv" +
	"alid path, length should <= 256\x02invalid path,path does not conform to" +
	" the win file path format specification\x02reload file path is required" +
	"\x02invalid reload file path, should <= 128\x02reload file path is not t" +
	"he absolute path\x02%[1]s sub path is system reserved path, do not allow" +
	" to use\x02memo is required, can not be empty\x02invalid memo, length sh" +
	"ould <= 200\x02resource name '%[1]s' is prefixed with '%[2]s' is reserve" +
	"d name, which is not allows to use\x02invalid name, length should >= 1" +
	"\x02invalid name, length should <= 128\x02invalid name: %[1]s, only allo" +
	"ws to include english、numbers、underscore (_)、hyphen (-), and must start " +
	"and end with an english、numbers\x02invalid name, length should >= 9 and " +
	"must start with prefix bk_bscp_ (ignore case)\x02invalid name: %[1]s, on" +
	"ly allows to include english、numbers、underscore (_), and must start with" +
	" prefix bk_bscp_ (ignore case)\x02invalid name: %[1]s, only allows to in" +
	"clude Chinese, English,numbers, underscore (_),hyphen (-), and must star" +
	"t and end with Chinese, English, or a number\x02invalid name, length sho" +
	"uld <= 64\x02invalid name %[1]s, name cannot all be '.'\x02invalid name " +
	"%[1]s, only allows Chinese, English, numbers, underscore (_), hyphen (-)" +
	", dot (.) and space\x02invalid namespace, length should >= 1\x02invalid " +
	"namespace, length should <= 128\x02invalid username, length should >= 1" +
	"\x02invalid username, length should <= 32\x02invalid environment name, l" +
	"ength should be greater than 0\x02invalid environment name, length shoul" +
	"d be less than or equal to 255\x02invalid environment name, only letters" +
	", numbers, underscores and hyphens are allowed,and it must start and end" +
	" with a letter or number\x02id can not be set\x02invalid biz id\x02inval" +
	"id spec, is nil\x02app spec is nil\x02unknown config type: %[1]s\x02app'" +
	"s type can not be updated\x02not support table config type for now\x02un" +
	"supported config type: %[1]s\x02unsupported app reload type: %[1]s\x02in" +
	"valid data-type\x02spec should be set\x02invalid commit spec's content i" +
	"d\x02commit spec's content is empty\x02verify Windows file paths failed," +
	" path: %[1]s, err: %[2]v\x02verify Unix file paths failed, path: %[1]s, " +
	"err: %[2]v\x02unsupported file format: %[1]s\x02unsupported file mode: %" +
	"[1]s\x02unsupported file charset: %[1]s\x02unsupported highlight style: " +
	"%[1]s\x02content id can not set\x02invalid content signature, should be " +
	"config's sha256 value\x02content signature should be lowercase\x02invali" +
	"d origin content signature, should be config's sha256 value\x02origin co" +
	"ntent signature should be lowercase\x02invalid app id\x02invalid config " +
	"item id\x02invalid environment type\x02name should be set\x02invalid att" +
	"achment biz id\x02invalid attachment project id\x02id should be set\x02k" +
	"ey should be set\x02ConfigFile\x02Process\x02Start\x02Stop\x02Restart" +
	"\x02Reload\x02Kill\x02Register\x02Unregister\x02ConfigPublish\x02ConfigG" +
	"enerate\x02ConfigCheck\x02Executing\x02ExecutionSuccessful\x02ExecutionF" +
	"ailed\x02PartialFailure\x02attachment should be set\x02revision should b" +
	"e set\x02template space id should be set\x02default_val %[1]s is not a n" +
	"umber type\x02invalid base directory\x02get absolute base path failed, b" +
	"aseDir: %[1]s, err: %[2]v\x02get absolute destination path failed, path:" +
	" %[1]s, err: %[2]v\x02calculate relative path failed, base: %[1]s, dst: " +
	"%[2]s, err: %[3]v\x02invalid file path\x02create parent directory failed" +
	", dir: %[1]s, err: %[2]v\x02create file failed, path: %[1]s, err: %[2]v" +
	"\x02write file failed, path: %[1]s, err: %[2]v\x02%[1]s and %[2]s path f" +
	"ile conflict"

var zhIndex = []uint32{ // 496 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000f, 0x00000022, 0x00000041,
	0x00000060, 0x00000085, 0x000000d1, 0x000000ea,
	0x00000109, 0x0000012e, 0x0000013b, 0x00000156,
	0x00000178, 0x000001ac, 0x000001ee, 0x00000221,
	0x00000246, 0x00000268, 0x0000027c, 0x00000298,
	0x000002b4, 0x000002cd, 0x000002f1, 0x0000032a,
	0x0000036a, 0x0000037d, 0x000003ae, 0x000003c2,
	0x000003e3, 0x00000404, 0x0000041a, 0x00000437,
	// Entry 20 - 3F
	0x0000045a, 0x00000477, 0x00000498, 0x000004b9,
	0x000004e8, 0x00000514, 0x00000543, 0x0000055d,
	0x0000057e, 0x0000057e, 0x000005b7, 0x000005c8,
	0x000005df, 0x00000634, 0x00000671, 0x0000068a,
	0x000006ac, 0x000006d6, 0x0000071c, 0x0000073a,
	0x0000075b, 0x00000778, 0x00000795, 0x000007b4,
	0x000007dc, 0x00000807, 0x00000826, 0x00000843,
	0x00000862, 0x00000888, 0x00000897, 0x00000897,
	// Entry 40 - 5F
	0x000008d4, 0x0000090a, 0x00000935, 0x0000095a,
	0x00000977, 0x00000994, 0x000009c5, 0x00000a12,
	0x00000a37, 0x00000a8b, 0x00000ae2, 0x00000b0d,
	0x00000b30, 0x00000ba1, 0x00000bc6, 0x00000beb,
	0x00000c00, 0x00000c22, 0x00000c3d, 0x00000c5e,
	0x00000c77, 0x00000ca8, 0x00000cdb, 0x00000d06,
	0x00000d2e, 0x00000d53, 0x00000d74, 0x00000d99,
	0x00000dc6, 0x00000dee, 0x00000e21, 0x00000e49,
	// Entry 60 - 7F
	0x00000e6e, 0x00000e93, 0x00000eb2, 0x00000ed9,
	0x00000f04, 0x00000f31, 0x00000f52, 0x00000f6b,
	0x00000f8a, 0x00000faf, 0x00000fce, 0x00000fe5,
	0x00001004, 0x00001017, 0x00001034, 0x0000104e,
	0x00001080, 0x000010aa, 0x000010cf, 0x000010f0,
	0x0000110f, 0x0000113f, 0x00001163, 0x00001182,
	0x000011bf, 0x000011fd, 0x00001278, 0x000012d2,
	0x00001333, 0x00001361, 0x00001380, 0x000013b7,
	// Entry 80 - 9F
	0x000013f4, 0x0000141e, 0x00001457, 0x000014b3,
	0x000014d4, 0x000014f5, 0x00001518, 0x00001539,
	0x0000155e, 0x00001579, 0x00001593, 0x000015b8,
	0x000015dd, 0x00001602, 0x00001627, 0x0000164b,
	0x0000166a, 0x0000168b, 0x000016a1, 0x000016ba,
	0x000016e0, 0x00001714, 0x0000172d, 0x00001797,
	0x000017e5, 0x00001835, 0x00001857, 0x00001895,
	0x000018c0, 0x000018e5, 0x0000190a, 0x00001923,
	// Entry A0 - BF
	0x0000194e, 0x00001979, 0x000019c5, 0x000019e7,
	0x00001a21, 0x00001a60, 0x00001a76, 0x00001ab8,
	0x00001aef, 0x00001b25, 0x00001b44, 0x00001b63,
	0x00001b96, 0x00001bbd, 0x00001be2, 0x00001bfe,
	0x00001c19, 0x00001c44, 0x00001c63, 0x00001c97,
	0x00001cc5, 0x00001ce7, 0x00001d0f, 0x00001d34,
	0x00001d53, 0x00001d82, 0x00001da7, 0x00001dd5,
	0x00001e06, 0x00001e37, 0x00001e5f, 0x00001e87,
	// Entry C0 - DF
	0x00001eb2, 0x00001ee6, 0x00001f0b, 0x00001f30,
	0x00001f67, 0x00001f8c, 0x00001fb7, 0x00001fe4,
	0x00002009, 0x00002038, 0x0000206b, 0x0000208a,
	0x000020b1, 0x000020d0, 0x000020f5, 0x00002129,
	0x0000214e, 0x0000216d, 0x00002180, 0x0000219d,
	0x000021ba, 0x000021ba, 0x000021ba, 0x000021ba,
	0x000021ba, 0x000021ba, 0x000021ba, 0x000021ba,
	0x000021d7, 0x00002202, 0x0000222a, 0x0000224f,
	// Entry E0 - FF
	0x0000227a, 0x000022b4, 0x000022cf, 0x000022ea,
	0x0000231a, 0x00002339, 0x00002351, 0x00002372,
	0x00002399, 0x000023bc, 0x000023de, 0x00002407,
	0x0000241d, 0x00002444, 0x0000247c, 0x0000249e,
	0x000024d1, 0x00002506, 0x00002541, 0x00002577,
	0x00002597, 0x000025b3, 0x000025e1, 0x0000260f,
	0x00002637, 0x00002656, 0x00002675, 0x000026a4,
	0x000026cf, 0x000026f4, 0x0000271f, 0x0000274d,
	// Entry 100 - 11F
	0x00002778, 0x000027ab, 0x000027de, 0x00002817,
	0x0000284e, 0x00002881, 0x000028b5, 0x000028e9,
	0x0000290f, 0x00002950, 0x0000297a, 0x000029af,
	0x000029b9, 0x000029c9, 0x000029d3, 0x000029dd,
	0x000029e7, 0x000029f1, 0x000029fb, 0x00002a08,
	0x00002a15, 0x00002a1f, 0x00002a29, 0x00002a36,
	0x00002a3d, 0x00002a47, 0x00002a51, 0x00002a58,
	0x00002a58, 0x00002a58, 0x00002a58, 0x00002a58,
	// Entry 120 - 13F
	0x00002a58, 0x00002a58, 0x00002a7c, 0x00002a95,
	0x00002ab9, 0x00002ad4, 0x00002af0, 0x00002b0b,
	0x00002b3b, 0x00002b68, 0x00002b7b, 0x00002b8b,
	0x00002bb8, 0x00002be8, 0x00002c13, 0x00002c3e,
	0x00002c70, 0x00002ca1, 0x00002cd2, 0x00002cfa,
	0x00002d28, 0x00002d56, 0x00002d7b, 0x00002da2,
	0x00002dcb, 0x00002df0, 0x00002e15, 0x00002e40,
	0x00002e59, 0x00002e83, 0x00002eb1, 0x00002ecd,
	// Entry 140 - 15F
	0x00002eda, 0x00002f08, 0x00002f44, 0x00002f60,
	0x00002fa1, 0x00002fcb, 0x0000300e, 0x00003040,
	0x0000305e, 0x00003088, 0x000030c1, 0x000030f2,
	0x0000311a, 0x0000313c, 0x0000316d, 0x000031a6,
	0x000031d7, 0x000031f6, 0x000031f6, 0x000031f6,
	0x0000322c, 0x0000324e, 0x00003295, 0x000032bf,
	0x000032ea, 0x00003303, 0x00003328, 0x0000333b,
	0x00003366, 0x00003390, 0x00003390, 0x00003390,
	// Entry 160 - 17F
	0x00003390, 0x00003390, 0x0000339d, 0x000033b6,
	0x000033d5, 0x000033f4, 0x00003426, 0x0000345c,
	0x000034ac, 0x000034ac, 0x000034ac, 0x000034ac,
	0x000034ac, 0x000034ac, 0x000034ac, 0x000034bc,
	0x000034cc, 0x000034dc, 0x000034ec, 0x000034ec,
	0x000034ec, 0x000034ec, 0x000034ec, 0x000034ec,
	0x00003535, 0x00003560, 0x00003586, 0x000035a6,
	0x000035d7, 0x000035fd, 0x0000362e, 0x00003654,
	// Entry 180 - 19F
	0x0000366b, 0x00003688, 0x000036ad, 0x000036ca,
	0x000036f5, 0x00003725, 0x0000374a, 0x00003774,
	0x000037a5, 0x000037da, 0x0000381b, 0x0000383d,
	0x0000384a, 0x00003869, 0x00003893, 0x000038a2,
	0x000038af, 0x000038c4, 0x000038d8, 0x000038f2,
	0x0000390a, 0x00003932, 0x0000395d, 0x00003990,
	0x000039c9, 0x000039e9, 0x00003a0b, 0x00003a44,
	0x00003a63, 0x00003a91, 0x00003abc, 0x00003af2,
	// Entry 1A0 - 1BF
	0x00003b13, 0x00003b35, 0x00003b86, 0x00003ba6,
	0x00003bc6, 0x00003c4d, 0x00003ca0, 0x00003d19,
	0x00003db2, 0x00003dd3, 0x00003e05, 0x00003e77,
	0x00003e9d, 0x00003ec5, 0x00003ee8, 0x00003f0c,
	0x00003f0c, 0x00003f0c, 0x00003f0c, 0x00003f1c,
	0x00003f31, 0x00003f3e, 0x00003f51, 0x00003f6f,
	0x00003f88, 0x00003fa4, 0x00003fc5, 0x00003fe6,
	0x00003fff, 0x0000400c, 0x0000401f, 0x0000402c,
	// Entry 1C0 - 1DF
	0x00004067, 0x0000409f, 0x000040c0, 0x000040e1,
	0x00004104, 0x00004124, 0x00004131, 0x00004160,
	0x00004176, 0x000041ae, 0x000041ca, 0x000041dc,
	0x000041f1, 0x000041f1, 0x000041f1, 0x000041f1,
	0x000041f1, 0x000041f1, 0x000041f1, 0x000041fe,
	0x00004205, 0x0000420c, 0x00004213, 0x0000421a,
	0x00004221, 0x0000422e, 0x00004235, 0x00004242,
	0x0000424f, 0x0000425c, 0x00004269, 0x00004276,
	// Entry 1E0 - 1FF
	0x00004283, 0x00004290, 0x0000429d, 0x0000429d,
	0x0000429d, 0x0000429d, 0x000042c2, 0x000042d5,
	0x00004310, 0x00004348, 0x00004386, 0x0000439c,
	0x000043ca, 0x000043f6, 0x00004422, 0x00004445,
} // Size: 2008 bytes

const zhData string = "" + // Size: 17477 bytes
	"\x02id不能为空\x02无效的文件名\x02读取文件失败, err: %[1]v\x02创建目录失败, err: %[1]v\x02创建临时" +
	"目录失败, err: %[1]v\x02解压文件失败, 文件 %[1]s 的大小超过了最大限制阈值 %[2]s\x02解压失败, err: " +
	"%[1]v\x02上传文件失败, err: %[1]v\x02获取模板配置失败, err: %[1]v\x02上传完成\x02上传完成, %[1" +
	"]d 失败\x02获取配置项失败, err: %[1]v\x02获取当前服务配置项总数失败, err: %[1]v\x02解压文件失败, 超过了" +
	"文件数量最大限制阈值 %[1]d\x02上传失败, 请确保文件大小不超过 %[1]s\x02获取模板数据失败, err: %[1]v\x02" +
	"不可见敏感信息无法导出\x02客户端 id 为空\x02批量删除配置项失败\x02批量恢复配置项失败\x02批量删除群组失败\x02灰度百分" +
	"比 key 必须是等于\x02灰度百分比 value 必须是有效的百分比 (1-99)\x02脚本id列表的长度为%[1]d, 长度范围必须" +
	"为[1,%[2]d]\x02批量删除失败\x02敏感数据不可见，无法查看实际内容\x02JSON数据不合法\x02json 格式化错误, e" +
	"rr: %[1]v\x02yaml 格式化错误, err: %[1]v\x02%[1]s 类型不支持\x02配置项 %[1]s 类型错误\x02" +
	"格式错误, 请检查键：%[1]s\x02配置项 %[1]s 格式错误\x02配置项 %[1]s json格式错误\x02配置项 %[1]s " +
	"yaml格式错误\x02配置项 %[1]s 密钥是否显示设置错误\x02配置项 %[1]s 的密钥类型不能为空\x02配置项 %[1]s 密钥类" +
	"型错误, err: %[2]v\x02配置项 %[1]s 值错误\x02请先填写配置项%[1]s的值\x02证书格式不正确，仅支持X.509" +
	"格式, err: %[1]v\x02key 不能为空\x02批量恢复 kv 失败\x02如果存在灰度百分比分组，则所有分组必须包含灰度百分比" +
	"标签\x02非灰度百分比标签在所有分组标签中必须一致\x02未定义的任务操作\x02从模板集中删除模板失败\x02模版变量名必须以%[1]s" +
	"前缀开头\x02全局变量id列表的长度为%[1]d, 长度范围必须为[1,%[2]d]\x02模板变量%[1]s类型错误\x02不支持的变量" +
	"类型：%[1]s\x02服务名称 %[1]s 已存在\x02服务别名 %[1]s 已存在\x02获取服务失败, err: %[1]v\x02" +
	"指定的类型与实际配置不匹配\x02删除服务相关资源失败, err: %[1]v\x02删除服务失败, err: %[1]v\x02ID为%[" +
	"1]d的服务不存在\x02业务查询失败, err: %[1]v\x02服务相关的业务 %[1]d 不存在\x02kv保持失败\x02此空间下配置" +
	"文件 %[1]s 已存在, 无法重复创建\x02按模板套餐ID列出模板套餐失败, err: %[1]v\x02更新服务模板绑定失败, err" +
	": %[1]v\x02列出模板空间失败, err: %[1]v\x02模板空间 %[1]s 不存在\x02模板套餐 %[1]s 不存在\x02获" +
	"取模板套餐下的模板失败, err: %[1]v\x02模板集%[2]s 中的模板文件 %[1]s 已被移除。请重新导入该集\x02获取模板版" +
	"本失败, err: %[1]v\x02模板文件 %[2]s 中的模板版本 %[1]s 已被删除。请重新导入该集合\x02模板文件 %[2]s" +
	" 中的版本号 %[1]s 不是最新版本。请重新导入该集合\x02统计服务配置数量失败, err: %[1]s\x02该服务 %[1]s 不是文件" +
	"类型\x02服务 %[1]s 的配置项总数（包括模板和非模板）超过单服务最大配置文件数量限制 %[2]d\x02校验分页参数失败, err:" +
	" %[1]v\x02获取配置模板失败, err: %[1]v\x02业务ID不能为空\x02至少需要一个配置模板组\x02配置模板ID不能为空" +
	"\x02配置模板版本ID不能为空\x02进程列表不能为空\x02根据操作范围获取进程失败, err: %[1]v\x02业务%[1]d在指定操作" +
	"范围内未找到进程\x02获取所有配置模板失败, err: %[1]v\x02范围内没有可执行的配置绑定\x02列出最新版本失败, err: " +
	"%[1]v\x02模板%[1]d未找到最新版本\x02列出配置模板失败, err: %[1]v\x02根据ID列出配置模板失败, err: %[" +
	"1]v\x02以下ID的配置模板未找到: %[1]s\x02根据模板进程ID列出进程失败, err: %[1]v\x02列出过滤后进程失败, e" +
	"rr: %[1]v\x02获取进程实例失败, err: %[1]v\x02列出配置实例失败, err: %[1]v\x02获取模板失败, err" +
	": %[1]v\x02根据cc进程ID未找到进程: %[1]d\x02获取最新模板版本失败, err: %[1]v\x02根据ID列出模板版本失" +
	"败, err: %[1]v\x02进程%[1]d不在配置模板中\x02任务存储未初始化\x02列出任务失败, err: %[1]v\x02获" +
	"取公共负载失败, err: %[1]v\x02获取任务失败, err: %[1]v\x02任务未找到: %[1]s\x02任务中未找到配置负" +
	"载\x02biz_id不能为空\x02template_content不能为空\x02cc_process_id不能为空\x02根据cc_p" +
	"rocess_id查询进程失败, err: %[1]v\x02根据cc_process_id未找到进程: %[1]d\x02查询进程实例失败, " +
	"err: %[1]v\x02展开ginclude失败, err: %[1]v\x02渲染模板失败, err: %[1]v\x02获取批次失败, " +
	"batch_id: %[1]d, err: %[2]v\x02批次%[1]d不是配置生成批次\x02列出任务失败, err: %[1]v\x02" +
	"批次 %[1]s 的任务总数为 0，没有可下发的任务\x02等待批次 %[1]s 的任务状态落库被取消, err: %[2]v\x02批次 " +
	"%[1]s 的成功任务数与批次总数不一致（已落库 %[2]s）,等待 %[3]s 后仍不一致, 已终止下发\x02批次 %[1]s 仍在执行中（" +
	"已完成 %[2]s）,请等待配置生成结束后再下发\x02批次 %[1]s 存在 %[2]s 个失败任务（成功 %[3]s）,需先重新生成配置" +
	"后再下发\x02获取源批次任务数据失败, err: %[1]v\x02创建批次失败, err: %[1]v\x02检查运行中的配置下发任务失" +
	"败, err: %[1]v\x02配置模板已有运行中的下发任务，请等待完成\x02获取配置模板%[1]d失败, err: %[2]v\x02" +
	"获取配置模板%[1]d的最新版本失败, err: %[2]v\x02配置模板%[1]d版本不是最新的, 当前: %[2]d, 最新: %[3" +
	"]d, 请重新生成配置\x02任务%[1]s的配置负载为空\x02任务%[1]s的进程负载为空\x02任务%[1]s的配置模板ID无效\x02批" +
	"次%[1]d未找到有效任务\x02获取任务批次失败, err: %[1]v\x02任务批次%[1]d不存在\x02未知操作类型: %[1]s" +
	"\x02重新生成任务失败, err: %[1]v\x02查询失败任务失败, err: %[1]v\x02重置重试计数失败, err: %[1]v" +
	"\x02重试失败任务失败, err: %[1]v\x02配置模板版本ID不是最新的\x02获取进程失败, err: %[1]v\x02业务%[1" +
	"]d部分进程未找到\x02无效的绑定关系\x02没有可创建的任务\x02不支持的配置任务模式: %[1]v\x02创建配置生成或校验任务失败, " +
	"err: %[1]v\x02任务中未找到负载\x02配置实例未找到, biz_id=%[1]d, config_template_id=%[2]" +
	"d, cc_process_id=%[3]d, module_inst_seq=%[4]d\x02模板与模板版本不匹配, template_id" +
	"=%[1]d, template_revision_id=%[2]d\x02下载模板配置失败, 模板id: %[1]d, name: %[2]s" +
	", path: %[3]s, err: %[4]v\x02获取配置项失败, err: %[1]v\x02此服务下的配置项 %[1]s 已存在，无" +
	"法再次创建\x02移除服务模板套餐失败, err: %[1]s\x02批量创建内容失败, err: %[1]s\x02删除模板变量失败, e" +
	"rr: %[1]s\x02配置项没有被删除\x02获取最新发布版本失败, err: %[1]v\x02获取已发布的配置失败, err: %[1]" +
	"v\x02恢复失败。具有相同路径的文件已存在，但未处于新状态\x02恢复配置项失败, err: %[1]v\x02获取大于最新发布版本的记录失败" +
	", err: %[1]v\x02配置项总数（包括模板和非模板）超出限制%[1]d\x02获取配置项数量\x02通过业务和服务ID获取模板绑定关系" +
	"失败, err: %[1]s\x02获取该服务下的引用模板集失败, err: %[1]s\x02按模板套餐ID列出模板套餐失败, err: " +
	"%[1]s\x02移除套餐失败, err: %[1]s\x02没有可用的空间或套餐\x02根据模板ID列出配置实例失败, err: %[1]v" +
	"\x02根据ID列出模板失败, err: %[1]v\x02查找拓扑摘要失败, err: %[1]v\x02没有可用的拓扑节点\x02未找到有效" +
	"的模块ID\x02获取所有模块详情失败, err: %[1]v\x02列出进程失败, err: %[1]v\x02根据唯一键获取配置模板失败" +
	", err: %[1]v\x02此业务%[1]d下已存在同名模板: %[2]s\x02获取模板集失败, err: %[1]v\x02创建模板和版" +
	"本失败, err: %[1]v\x02创建配置模板失败, err: %[1]v\x02创建模板失败, err: %[1]v\x02版本号 %" +
	"[1]s 已存在，请更换后重试\x02创建模板版本失败, err: %[1]v\x02模板集批量添加模板失败, err: %[1]s\x02获取" +
	"默认模板配置空间失败, err: %[1]v\x02创建默认模板配置空间失败, err: %[1]v\x02获取默认模板集失败, err: " +
	"%[1]v\x02创建默认模板集失败, err: %[1]v\x02获取所有服务模板失败, err: %[1]v\x02按服务模板批量处理进程失" +
	"败, err: %[1]v\x02列出进程模板失败, err: %[1]v\x02列出服务实例失败, err: %[1]v\x02按服务实例" +
	"批量统计进程数失败, err: %[1]v\x02列出进程实例失败, err: %[1]v\x02获取业务对象属性失败, err: %[1]" +
	"v\x02根据ID获取配置模板失败, err: %[1]v\x02更新配置模板失败, err: %[1]v\x02根据CC进程ID列出进程失败," +
	" err: %[1]v\x02根据进程模板ID列出进程失败, err: %[1]v\x02更新模板失败, err: %[1]v\x02根据ID获" +
	"取模板失败, err: %[1]v\x02删除模板失败, err: %[1]v\x02删除模板版本失败, err: %[1]v\x02从所有" +
	"模板集中删除模板失败, err: %[1]v\x02删除配置模板失败, err: %[1]v\x02提交事务失败, err: %[1]v" +
	"\x02路径不能为空\x02路径不能包含null字符\x02路径包含无效段: %[1]s\x02脚本名称 %[1]s 已存在\x02获取排除后的" +
	"脚本失败, err: %[1]s\x02检索引用的脚本失败, err: %[1]s\x02获取 kv (%[1]d) 失败, err: %[" +
	"2]v\x02获取服务失败, key: %[1]s, err: %[2]v\x02kv 类型与服务类型中定义的数据类型不匹配\x02创建kv失败" +
	", err: %[1]v\x02更新kv失败, err: %[1]v\x02获取过期证书列表失败，错误：%[1]v\x02获取键值失败, err" +
	": %[1]v\x02不是kv类型的服务\x02获取kv列表失败, err: %[1]v\x02批量导入KV配置失败, err: %[1]v" +
	"\x02配置项 %[1]s 的类型不正确\x02清除草稿区失败, err: %[1]v\x02批量更新vault失败，错误：%[1]v\x02存" +
	"在重复的 %[1]s\x02获取排除后的kv失败, err: %[1]s\x02统计未删除的kV文件数量失败，错误：%[1]v\x02配置项" +
	"总数超出限制 %[1]d\x02根据进程ID获取进程实例失败, err: %[1]v\x02根据CC进程ID列出配置模板失败, err: %" +
	"[1]v\x02根据CC模板进程ID列出配置模板失败, err: %[1]v\x02指定了ProcessInstanceId时只允许一个Proc" +
	"essId\x02不支持的操作类型: %[1]v\x02不支持query_status操作\x02操作范围内未找到匹配的进程实例\x02根据ID" +
	"s获取进程实例失败, err: %[1]v\x02以下ID的进程实例未找到: %[1]v\x02根据ID未找到进程: %[1]d\x02获取进程" +
	"失败, err: %[1]v\x02业务%[1]d在指定进程ID下未找到进程\x02以下进程ID未找到进程实例: %[1]v\x02创建任务" +
	"批次失败, err: %[1]v\x02更新进程实例状态失败, err: %[1]v\x02processMap中未找到进程, proces" +
	"sID=%[1]d\x02构建进程操作任务失败, err: %[1]v\x02列出进程过滤选项(集群)失败, err: %[1]v\x02列出进" +
	"程过滤选项(模块)失败, err: %[1]v\x02列出进程过滤选项(服务实例)失败, err: %[1]v\x02列出进程过滤选项(CC" +
	"进程ID)失败, err: %[1]v\x02列出进程过滤选项(别名)失败, err: %[1]v\x02从任务存储列出失败任务失败, er" +
	"r: %[1]v\x02为进程实例拓扑列出进程失败, err: %[1]v\x02不支持删除的管理状态: %[1]s\x02不支持删除的进程状态" +
	": status=%[1]s managedStatus=%[2]s\x02删除进程实例%[1]d失败, err: %[2]v\x02列出进程过" +
	"滤选项(内网IP)失败, err: %[1]v\x02运行中\x02部分运行中\x02启动中\x02重启中\x02停止中\x02重载中" +
	"\x02未运行\x02启动托管\x02停止托管\x02已托管\x02未托管\x02部分托管\x02正常\x02已删除\x02有更新\x02异常" +
	"\x02版本%[1]s已弃用，无法提交\x02当前有版本在上线\x02版本%[1]s已弃用，无法撤消\x02上线状态无效：%[1]s\x02没有" +
	"权限批准此工单\x02版本名称%[1]s已存在\x02不允许撤销，当前上线状态为：%[1]s\x02无法拒绝，当前上线状态为：%[1]s" +
	"\x02原因不能为空\x02无权限审批\x02无法通过，当前上线状态为：%[1]s\x02不允许上线，当前上线状态为：%[1]s\x02此单据已" +
	"撤销，无需进一步处理\x02此单据已结束，无需进一步处理\x02此单据已撤销，无效的单据状态: %[1]s\x02此单据已被拒绝，无需进一步" +
	"处理。\x02此单据已审批完成，无需进一步处理\x02创建发布失败，存在文件冲突\x02创建发布失败，存在证书过期问题\x02获取服务关联的" +
	"套餐失败, err: %[1]v\x02获取模板文件失败, err: %[1]v\x02业务%[1]d未开启进程配置视图\x02创建同步CM" +
	"DB任务失败, err: %[1]v\x02获取业务数据失败, err: %[1]v\x02列出任务批次失败, err: %[1]v\x02列出" +
	"不同的执行者失败, err: %[1]v\x02任务存储未初始化\x02获取任务批次%[1]d失败, err: %[2]v\x02从任务存储" +
	"列出任务失败, err: %[1]v\x02列出任务返回nil分页\x02任务为空\x02从任务获取公共负载失败, err: %[1]v" +
	"\x02从任务存储按状态%[1]s列出任务失败, err: %[2]v\x02无效的%[1]s格式: %[2]v\x02重置任务批次重试计数失败" +
	", batchID: %[1]d, err: %[2]v\x02未找到任务%[1]s的操作进程步骤\x02从任务步骤获取操作负载失败, task" +
	"ID: %[1]s, err: %[2]v\x02根据ID获取进程实例%[1]d失败, err: %[2]v\x02进程实例ID %[1]d不存" +
	"在\x02重试失败任务%[1]s失败, err: %[2]v\x02按模板集ID获取应用程序模板绑定, err: %[1]s\x02批量更新" +
	"应用模板绑定失败, err: %[1]s\x02获取模板集数据失败, err: %[1]s\x02此模板集下没有模板文件\x02从模板套餐中" +
	"删除模板失败, err: %[1]v\x02按模板集ID获取应用程序模板绑定, err: %[1]v\x02批量更新应用模板绑定失败, er" +
	"r: %[1]v\x02列出模板失败, err: %[1]v\x02按服务ID列出应用模板绑定失败, err: %[1]s\x02获取模板集失败" +
	", err: %[1]s\x02模板套餐 %[1]s 超过单套餐最大配置文件数量限制 %[2]d\x02按服务ID列出服务失败, err: %[" +
	"1]s\x02统计服务配置数量失败, err: %[1]s\x02模板套餐数据为空\x02列出模板数据失败, err: %[1]s\x02模板数" +
	"据为空\x02列出模板版本数据失败, err: %[1]s\x02同名的模版变量名称%[1]s已存在\x02服务为空\x02创建失败, er" +
	"r: %[1]v\x02创建服务失败, err: %[1]v\x02更新服务失败, err: %[1]s\x02统计服务 %[1]d 的配置项失" +
	"败, err: %[2]v\x02获取服务 %[1]d 的模板绑定失败,  err: %[2]v\x02服务 %[1]d 的配置项总数（包括" +
	"模板和非模板）超出限制 %[2]d\x02脚本不存在\x02未命名版本\x02appID不能为0\x02bizID不能为0\x02模板套餐 " +
	"%[1]d's 超过单套餐最大配置文件数量限制 %[2]d\x02验证模板是否存在失败, err: %[1]v\x02%[1]v 中的模板空间 " +
	"ID 不存在\x02%[1]v 中的模板 ID 不存在\x02验证模板版本是否存在失败, err: %[1]v\x02%[1]v 中的模板版本 " +
	"ID 不存在\x02验证模板套餐是否存在失败, err: %[1]v\x02%[1]v 中的模板套餐 ID 不存在\x02模板 %[1]d 不存" +
	"在\x02模板版本 %[1]d 不存在\x02获取模板版本失败, err: %[1]v\x02模板套餐 %[1]d 不存在\x02统计模板套" +
	"餐数量失败, err: %[1]v\x02模板空间下有模板套餐, 需要先删除\x02获取模板数量失败, err: %[1]v\x02模板空间" +
	"下有模板, 需要先删除\x02验证模板套餐中的模板失败, err: %[1]v\x02%[1]v 中的模板 ID 不属于模板套餐 ID %[" +
	"2]d\x02从 kv.Data 获取“kv_type”作为字符串失败, err: %[1]v\x02值类型断言失败, err: %[1]v" +
	"\x02授权失败\x02获取权限失败, err: %[1]v\x02grpc 状态详细信息失败, err: %[1]v\x02db操作失败" +
	"\x02无效参数\x02id不应该被设置\x02spec没有被设置\x02attachment没有被设置\x02revision没有被设置" +
	"\x02路径 %[1]s 无效，长度应为 >= 1\x02路径 %[1]s 无效，长度应为 <= 1024\x02路径 %[1]s 无效，路径必" +
	"须以“/”开头\x02路径 %[1]s 无效，路径不能包含连续的“/”\x02路径无效, 长度应为 >= 1\x02路径无效, 长度应为 <" +
	"= 256\x02路径无效, 路径不符合win文件路径格式规范\x02需要重新加载文件路径\x02重新加载文件路径无效, 应该 <= 128" +
	"\x02重新加载文件路径不是绝对路径\x02%[1]s 子路径为系统保留路径, 不允许使用\x02描述为必填项, 不能为空\x02描述无效, 长" +
	"度应为 <= 200\x02资源名称“%[1]s”以“%[2]s”为前缀, 是保留名称, 不允许使用\x02名称无效, 长度应为 >= 1" +
	"\x02无效名称, 长度应该<=128\x02无效名称：%[1]s, 只允许包含英文、数字、下划线（_）、连字符（-）, 且必须以英文、数字开头" +
	"和结尾\x02无效名称, 长度应该>=9且必须以bk_bscp_前缀开头（忽略大小写）\x02无效名称：%[1]s, 只允许英文、数字、下划" +
	"线（_）, 且必须以bk_bscp_前缀开头（忽略大小写）\x02无效名称：%[1]s, 只允许包含中文、英文、数字、下划线（_）、连字符（" +
	"-）, 且必须以中文、英文或数字开头和结尾\x02名称无效, 长度应为 <= 64\x02名称 %[1]s 无效, 名称不能全部为“.”\x02" +
	"无效名称 %[1]s, 只允许中文、英文、数字、下划线（_）、连字符（-）、点（.）和空格\x02命名空间无效, 长度应为 >= 1\x02" +
	"命名空间无效, 长度应为 <= 128\x02用户名无效, 长度应为 >= 1\x02用户名无效, 长度应为 <= 32\x02ID 不能为" +
	"空\x02无法验证业务ID\x02参数为空\x02服务参数为空\x02未知的配置类型：%[1]s\x02服务类型不能编辑\x02暂不支持表配" +
	"置类型\x02不支持的配置类型：%[1]s\x02不支持的服务类型：%[1]s\x02无法验证数据类型\x02参数为空\x02无法验证参数" +
	"\x02参数为空\x02验证 Windows 文件路径失败, path: %[1]s, err: %[2]v\x02验证 Unix 文件路径失败" +
	", path: %[1]s, err: %[2]v\x02不支持的文件格式：%[1]s\x02不支持的文件模式：%[1]s\x02不支持的文件字" +
	"符集: %[1]s\x02不支持的高亮样式: %[1]s\x02参数为空\x02内容签名无效, 应为配置的 sha256 值\x02内容签名" +
	"应小写\x02无效的原始内容签名, 应为配置的 sha256 值\x02原始内容签名应小写\x02无效的服务ID\x02无效的配置项ID" +
	"\x02配置文件\x02进程\x02启动\x02停止\x02重启\x02重载\x02强制停止\x02托管\x02取消托管\x02配置下发\x02" +
	"配置生成\x02配置检查\x02正在执行\x02执行成功\x02执行失败\x02部分失败\x02default_val %[1]s 不是数字" +
	"类型\x02无效的根目录\x02获取绝对基本路径失败, baseDir: %[1]s, err: %[2]v\x02获取绝对目标路径失败, " +
	"path: %[1]s, err: %[2]v\x02计算相对路径失败, base: %[1]s, dst: %[2]s, err: %[3]v" +
	"\x02无效的文件路径\x02创建父目录失败, dir: %[1]s, err: %[2]v\x02创建文件失败, path: %[1]s, e" +
	"rr: %[2]v\x02文件写入失败, path: %[1]s, err: %[2]v\x02%[1]s 与 %[2]s 路径文件冲突"

	// Total table size 42683 bytes (41KiB); checksum: 74BB7A34
