// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.1
// source: template_variable.proto

package pbtv

import (
	base "github.com/TencentBlueKing/bk-bscp/pkg/protocol/core/base"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TemplateVariable source resource reference: pkg/dal/table/template_variable.go
type TemplateVariable struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            uint32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Spec          *TemplateVariableSpec       `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Attachment    *TemplateVariableAttachment `protobuf:"bytes,3,opt,name=attachment,proto3" json:"attachment,omitempty"`
	Revision      *base.Revision              `protobuf:"bytes,4,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateVariable) Reset() {
	*x = TemplateVariable{}
	mi := &file_template_variable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateVariable) ProtoMessage() {}

func (x *TemplateVariable) ProtoReflect() protoreflect.Message {
	mi := &file_template_variable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateVariable.ProtoReflect.Descriptor instead.
func (*TemplateVariable) Descriptor() ([]byte, []int) {
	return file_template_variable_proto_rawDescGZIP(), []int{0}
}

func (x *TemplateVariable) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TemplateVariable) GetSpec() *TemplateVariableSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *TemplateVariable) GetAttachment() *TemplateVariableAttachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *TemplateVariable) GetRevision() *base.Revision {
	if x != nil {
		return x.Revision
	}
	return nil
}

// TemplateVariableSpec source resource reference: pkg/dal/table/template_variable.go
type TemplateVariableSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DefaultVal    string                 `protobuf:"bytes,3,opt,name=default_val,json=defaultVal,proto3" json:"default_val,omitempty"`
	Memo          string                 `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateVariableSpec) Reset() {
	*x = TemplateVariableSpec{}
	mi := &file_template_variable_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateVariableSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateVariableSpec) ProtoMessage() {}

func (x *TemplateVariableSpec) ProtoReflect() protoreflect.Message {
	mi := &file_template_variable_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateVariableSpec.ProtoReflect.Descriptor instead.
func (*TemplateVariableSpec) Descriptor() ([]byte, []int) {
	return file_template_variable_proto_rawDescGZIP(), []int{1}
}

func (x *TemplateVariableSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateVariableSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TemplateVariableSpec) GetDefaultVal() string {
	if x != nil {
		return x.DefaultVal
	}
	return ""
}

func (x *TemplateVariableSpec) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

// TemplateVariableAttachment source resource reference: pkg/dal/table/template_variable.go
type TemplateVariableAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         uint32                 `protobuf:"varint,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateVariableAttachment) Reset() {
	*x = TemplateVariableAttachment{}
	mi := &file_template_variable_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateVariableAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateVariableAttachment) ProtoMessage() {}

func (x *TemplateVariableAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_template_variable_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateVariableAttachment.ProtoReflect.Descriptor instead.
func (*TemplateVariableAttachment) Descriptor() ([]byte, []int) {
	return file_template_variable_proto_rawDescGZIP(), []int{2}
}

func (x *TemplateVariableAttachment) GetBizId() uint32 {
	if x != nil {
		return x.BizId
	}
	return 0
}

var File_template_variable_proto protoreflect.FileDescriptor

const file_template_variable_proto_rawDesc = "" +
	"\n" +
	"\x17template_variable.proto\x12\x04pbtv\x1a!pkg/protocol/core/base/base.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xd1\x01\n" +
	"\x10TemplateVariable\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\rB\r\x92A\n" +
	"2\b变量IDR\x02id\x12.\n" +
	"\x04spec\x18\x02 \x01(\v2\x1a.pbtv.TemplateVariableSpecR\x04spec\x12@\n" +
	"\n" +
	"attachment\x18\x03 \x01(\v2 .pbtv.TemplateVariableAttachmentR\n" +
	"attachment\x12,\n" +
	"\brevision\x18\x04 \x01(\v2\x10.pbbase.RevisionR\brevision\"\xce\x01\n" +
	"\x14TemplateVariableSpec\x12%\n" +
	"\x04name\x18\x01 \x01(\tB\x11\x92A\x0e2\f变量名称R\x04name\x127\n" +
	"\x04type\x18\x02 \x01(\tB#\x92A 2\x1e变量类型：string、numberR\x04type\x12/\n" +
	"\vdefault_val\x18\x03 \x01(\tB\x0e\x92A\v2\t默认值R\n" +
	"defaultVal\x12%\n" +
	"\x04memo\x18\x04 \x01(\tB\x11\x92A\x0e2\f变量描述R\x04memo\"B\n" +
	"\x1aTemplateVariableAttachment\x12$\n" +
	"\x06biz_id\x18\x01 \x01(\rB\r\x92A\n" +
	"2\b业务IDR\x05bizIdBMZKgithub.com/TencentBlueKing/bk-bscp/pkg/protocol/core/template-variable;pbtvb\x06proto3"

var (
	file_template_variable_proto_rawDescOnce sync.Once
	file_template_variable_proto_rawDescData []byte
)

func file_template_variable_proto_rawDescGZIP() []byte {
	file_template_variable_proto_rawDescOnce.Do(func() {
		file_template_variable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_template_variable_proto_rawDesc), len(file_template_variable_proto_rawDesc)))
	})
	return file_template_variable_proto_rawDescData
}

var file_template_variable_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_template_variable_proto_goTypes = []any{
	(*TemplateVariable)(nil),           // 0: pbtv.TemplateVariable
	(*TemplateVariableSpec)(nil),       // 1: pbtv.TemplateVariableSpec
	(*TemplateVariableAttachment)(nil), // 2: pbtv.TemplateVariableAttachment
	(*base.Revision)(nil),              // 3: pbbase.Revision
}
var file_template_variable_proto_depIdxs = []int32{
	1, // 0: pbtv.TemplateVariable.spec:type_name -> pbtv.TemplateVariableSpec
	2, // 1: pbtv.TemplateVariable.attachment:type_name -> pbtv.TemplateVariableAttachment
	3, // 2: pbtv.TemplateVariable.revision:type_name -> pbbase.Revision
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_template_variable_proto_init() }
func file_template_variable_proto_init() {
	if File_template_variable_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_template_variable_proto_rawDesc), len(file_template_variable_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_template_variable_proto_goTypes,
		DependencyIndexes: file_template_variable_proto_depIdxs,
		MessageInfos:      file_template_variable_proto_msgTypes,
	}.Build()
	File_template_variable_proto = out.File
	file_template_variable_proto_goTypes = nil
	file_template_variable_proto_depIdxs = nil
}
