# BSCP Single-tenant to Multi-tenant Migration Configuration
# 单租户到多租户数据迁移配置文件

# Migration settings
# 迁移设置
migration:
  # Target tenant ID to set for all migrated records
  # 目标租户ID，将填充到所有迁移记录中
  target_tenant_id: "10001"
  
  # Business IDs to migrate (if not specified, migrate all businesses)
  # 要迁移的业务ID列表（如果不指定，则迁移所有业务）
  # This allows migrating data for specific businesses only
  # 支持按业务维度迁移数据
  # biz_ids:
  #   - 100
  #   - 200
  #   - 300
  
  # Number of records to process in each batch
  # 每批处理的记录数
  batch_size: 1000
  
  # If true, continue migration even if some records fail
  # 如果为 true，即使部分记录失败也继续迁移
  continue_on_error: false

# Source environment configuration
# 源环境配置
source:
  mysql:
    # MySQL endpoints in host:port format
    endpoints:
      - "localhost:3306"
    database: ""
    user: "root"
    password: ""
    # Optional connection settings
    dialTimeoutSec: 15
    readTimeoutSec: 30
    writeTimeoutSec: 30
    maxOpenConn: 50
    maxIdleConn: 10
  
  vault:
    # Vault server address
    address: "http://localhost:8200"
    # Vault access token
    token: "root-token"

# Target environment configuration
# 目标环境配置
target:
  mysql:
    endpoints:
      - "localhost:3306"
    database: ""
    user: "root"
    password: ""
    dialTimeoutSec: 15
    readTimeoutSec: 30
    writeTimeoutSec: 30
    maxOpenConn: 50
    maxIdleConn: 10
  
  vault:
    address: "http://localhost:8200"
    token: "root-token"

# Logging configuration
# 日志配置
log:
  # Log level: debug, info, warn, error
  level: "info"
  # If true, logs to stderr
  toStdErr: true
