// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.1
// source: client_event.proto

package pbce

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientEvent source resource reference: pkg/dal/table/client-event.go
type ClientEvent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Spec                *ClientEventSpec       `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Attachment          *ClientEventAttachment `protobuf:"bytes,3,opt,name=attachment,proto3" json:"attachment,omitempty"`
	HeartbeatTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=heartbeat_time,json=heartbeatTime,proto3" json:"heartbeat_time,omitempty"`
	MessageType         string                 `protobuf:"bytes,5,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	OriginalReleaseName string                 `protobuf:"bytes,6,opt,name=original_release_name,json=originalReleaseName,proto3" json:"original_release_name,omitempty"`
	TargetReleaseName   string                 `protobuf:"bytes,7,opt,name=target_release_name,json=targetReleaseName,proto3" json:"target_release_name,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_client_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_client_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_client_event_proto_rawDescGZIP(), []int{0}
}

func (x *ClientEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientEvent) GetSpec() *ClientEventSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ClientEvent) GetAttachment() *ClientEventAttachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *ClientEvent) GetHeartbeatTime() *timestamppb.Timestamp {
	if x != nil {
		return x.HeartbeatTime
	}
	return nil
}

func (x *ClientEvent) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *ClientEvent) GetOriginalReleaseName() string {
	if x != nil {
		return x.OriginalReleaseName
	}
	return ""
}

func (x *ClientEvent) GetTargetReleaseName() string {
	if x != nil {
		return x.TargetReleaseName
	}
	return ""
}

// ClientEventSpec source resource reference: pkg/dal/table/client-event.go
type ClientEventSpec struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	OriginalReleaseId         uint32                 `protobuf:"varint,1,opt,name=original_release_id,json=originalReleaseId,proto3" json:"original_release_id,omitempty"`
	TargetReleaseId           uint32                 `protobuf:"varint,2,opt,name=target_release_id,json=targetReleaseId,proto3" json:"target_release_id,omitempty"`
	StartTime                 *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime                   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TotalSeconds              float64                `protobuf:"fixed64,5,opt,name=total_seconds,json=totalSeconds,proto3" json:"total_seconds,omitempty"`
	TotalFileSize             float64                `protobuf:"fixed64,6,opt,name=total_file_size,json=totalFileSize,proto3" json:"total_file_size,omitempty"`
	DownloadFileSize          float64                `protobuf:"fixed64,7,opt,name=download_file_size,json=downloadFileSize,proto3" json:"download_file_size,omitempty"`
	TotalFileNum              uint32                 `protobuf:"varint,8,opt,name=total_file_num,json=totalFileNum,proto3" json:"total_file_num,omitempty"`
	DownloadFileNum           uint32                 `protobuf:"varint,9,opt,name=download_file_num,json=downloadFileNum,proto3" json:"download_file_num,omitempty"`
	ReleaseChangeStatus       string                 `protobuf:"bytes,10,opt,name=release_change_status,json=releaseChangeStatus,proto3" json:"release_change_status,omitempty"`
	ReleaseChangeFailedReason string                 `protobuf:"bytes,11,opt,name=release_change_failed_reason,json=releaseChangeFailedReason,proto3" json:"release_change_failed_reason,omitempty"`
	FailedDetailReason        string                 `protobuf:"bytes,12,opt,name=failed_detail_reason,json=failedDetailReason,proto3" json:"failed_detail_reason,omitempty"`
	SpecificFailedReason      string                 `protobuf:"bytes,13,opt,name=specific_failed_reason,json=specificFailedReason,proto3" json:"specific_failed_reason,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ClientEventSpec) Reset() {
	*x = ClientEventSpec{}
	mi := &file_client_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEventSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEventSpec) ProtoMessage() {}

func (x *ClientEventSpec) ProtoReflect() protoreflect.Message {
	mi := &file_client_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEventSpec.ProtoReflect.Descriptor instead.
func (*ClientEventSpec) Descriptor() ([]byte, []int) {
	return file_client_event_proto_rawDescGZIP(), []int{1}
}

func (x *ClientEventSpec) GetOriginalReleaseId() uint32 {
	if x != nil {
		return x.OriginalReleaseId
	}
	return 0
}

func (x *ClientEventSpec) GetTargetReleaseId() uint32 {
	if x != nil {
		return x.TargetReleaseId
	}
	return 0
}

func (x *ClientEventSpec) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ClientEventSpec) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ClientEventSpec) GetTotalSeconds() float64 {
	if x != nil {
		return x.TotalSeconds
	}
	return 0
}

func (x *ClientEventSpec) GetTotalFileSize() float64 {
	if x != nil {
		return x.TotalFileSize
	}
	return 0
}

func (x *ClientEventSpec) GetDownloadFileSize() float64 {
	if x != nil {
		return x.DownloadFileSize
	}
	return 0
}

func (x *ClientEventSpec) GetTotalFileNum() uint32 {
	if x != nil {
		return x.TotalFileNum
	}
	return 0
}

func (x *ClientEventSpec) GetDownloadFileNum() uint32 {
	if x != nil {
		return x.DownloadFileNum
	}
	return 0
}

func (x *ClientEventSpec) GetReleaseChangeStatus() string {
	if x != nil {
		return x.ReleaseChangeStatus
	}
	return ""
}

func (x *ClientEventSpec) GetReleaseChangeFailedReason() string {
	if x != nil {
		return x.ReleaseChangeFailedReason
	}
	return ""
}

func (x *ClientEventSpec) GetFailedDetailReason() string {
	if x != nil {
		return x.FailedDetailReason
	}
	return ""
}

func (x *ClientEventSpec) GetSpecificFailedReason() string {
	if x != nil {
		return x.SpecificFailedReason
	}
	return ""
}

// ClientEventAttachment source resource reference: pkg/dal/table/client-event.go
type ClientEventAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	BizId         uint32                 `protobuf:"varint,3,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	AppId         uint32                 `protobuf:"varint,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ClientMode    string                 `protobuf:"bytes,5,opt,name=client_mode,json=clientMode,proto3" json:"client_mode,omitempty"`
	CursorId      string                 `protobuf:"bytes,6,opt,name=cursor_id,json=cursorId,proto3" json:"cursor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEventAttachment) Reset() {
	*x = ClientEventAttachment{}
	mi := &file_client_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEventAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEventAttachment) ProtoMessage() {}

func (x *ClientEventAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_client_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEventAttachment.ProtoReflect.Descriptor instead.
func (*ClientEventAttachment) Descriptor() ([]byte, []int) {
	return file_client_event_proto_rawDescGZIP(), []int{2}
}

func (x *ClientEventAttachment) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ClientEventAttachment) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ClientEventAttachment) GetBizId() uint32 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *ClientEventAttachment) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ClientEventAttachment) GetClientMode() string {
	if x != nil {
		return x.ClientMode
	}
	return ""
}

func (x *ClientEventAttachment) GetCursorId() string {
	if x != nil {
		return x.CursorId
	}
	return ""
}

var File_client_event_proto protoreflect.FileDescriptor

const file_client_event_proto_rawDesc = "" +
	"\n" +
	"\x12client_event.proto\x12\x04pbce\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xe7\x02\n" +
	"\vClientEvent\x12&\n" +
	"\x02id\x18\x01 \x01(\rB\x16\x92A\x132\x11客户端事件IDR\x02id\x12)\n" +
	"\x04spec\x18\x02 \x01(\v2\x15.pbce.ClientEventSpecR\x04spec\x12;\n" +
	"\n" +
	"attachment\x18\x03 \x01(\v2\x1b.pbce.ClientEventAttachmentR\n" +
	"attachment\x12A\n" +
	"\x0eheartbeat_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rheartbeatTime\x12!\n" +
	"\fmessage_type\x18\x05 \x01(\tR\vmessageType\x122\n" +
	"\x15original_release_name\x18\x06 \x01(\tR\x13originalReleaseName\x12.\n" +
	"\x13target_release_name\x18\a \x01(\tR\x11targetReleaseName\"\xb4\a\n" +
	"\x0fClientEventSpec\x12@\n" +
	"\x13original_release_id\x18\x01 \x01(\rB\x10\x92A\r2\v源版本IDR\x11originalReleaseId\x12?\n" +
	"\x11target_release_id\x18\x02 \x01(\rB\x13\x92A\x102\x0e模板版本IDR\x0ftargetReleaseId\x12L\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x11\x92A\x0e2\f开始时间R\tstartTime\x12H\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x11\x92A\x0e2\f结束时间R\aendTime\x123\n" +
	"\rtotal_seconds\x18\x05 \x01(\x01B\x0e\x92A\v2\t总耗时R\ftotalSeconds\x12<\n" +
	"\x0ftotal_file_size\x18\x06 \x01(\x01B\x14\x92A\x112\x0f总文件大小R\rtotalFileSize\x12H\n" +
	"\x12download_file_size\x18\a \x01(\x01B\x1a\x92A\x172\x15下载的文件大小R\x10downloadFileSize\x127\n" +
	"\x0etotal_file_num\x18\b \x01(\rB\x11\x92A\x0e2\f总文件数R\ftotalFileNum\x12C\n" +
	"\x11download_file_num\x18\t \x01(\rB\x17\x92A\x142\x12下载的文件数R\x0fdownloadFileNum\x12K\n" +
	"\x15release_change_status\x18\n" +
	" \x01(\tB\x17\x92A\x142\x12配置拉取状态R\x13releaseChangeStatus\x12^\n" +
	"\x1crelease_change_failed_reason\x18\v \x01(\tB\x1d\x92A\x1a2\x18发布变更失败原因R\x19releaseChangeFailedReason\x12O\n" +
	"\x14failed_detail_reason\x18\f \x01(\tB\x1d\x92A\x1a2\x18失败详细信息原因R\x12failedDetailReason\x12M\n" +
	"\x16specific_failed_reason\x18\r \x01(\tB\x17\x92A\x142\x12具体失败原因R\x14specificFailedReason\"\xa6\x02\n" +
	"\x15ClientEventAttachment\x12-\n" +
	"\tclient_id\x18\x01 \x01(\rB\x10\x92A\r2\v客户端IDR\bclientId\x12#\n" +
	"\x03uid\x18\x02 \x01(\tB\x11\x92A\x0e2\f客户端UIDR\x03uid\x12$\n" +
	"\x06biz_id\x18\x03 \x01(\rB\r\x92A\n" +
	"2\b业务IDR\x05bizId\x12$\n" +
	"\x06app_id\x18\x04 \x01(\rB\r\x92A\n" +
	"2\b服务IDR\x05appId\x12A\n" +
	"\vclient_mode\x18\x05 \x01(\tB \x92A\x1d2\x1b拉取方式：pull、watchR\n" +
	"clientMode\x12*\n" +
	"\tcursor_id\x18\x06 \x01(\tB\r\x92A\n" +
	"2\b事件IDR\bcursorIdBHZFgithub.com/TencentBlueKing/bk-bscp/pkg/protocol/core/client-event;pbceb\x06proto3"

var (
	file_client_event_proto_rawDescOnce sync.Once
	file_client_event_proto_rawDescData []byte
)

func file_client_event_proto_rawDescGZIP() []byte {
	file_client_event_proto_rawDescOnce.Do(func() {
		file_client_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_event_proto_rawDesc), len(file_client_event_proto_rawDesc)))
	})
	return file_client_event_proto_rawDescData
}

var file_client_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_client_event_proto_goTypes = []any{
	(*ClientEvent)(nil),           // 0: pbce.ClientEvent
	(*ClientEventSpec)(nil),       // 1: pbce.ClientEventSpec
	(*ClientEventAttachment)(nil), // 2: pbce.ClientEventAttachment
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_client_event_proto_depIdxs = []int32{
	1, // 0: pbce.ClientEvent.spec:type_name -> pbce.ClientEventSpec
	2, // 1: pbce.ClientEvent.attachment:type_name -> pbce.ClientEventAttachment
	3, // 2: pbce.ClientEvent.heartbeat_time:type_name -> google.protobuf.Timestamp
	3, // 3: pbce.ClientEventSpec.start_time:type_name -> google.protobuf.Timestamp
	3, // 4: pbce.ClientEventSpec.end_time:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_client_event_proto_init() }
func file_client_event_proto_init() {
	if File_client_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_event_proto_rawDesc), len(file_client_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_event_proto_goTypes,
		DependencyIndexes: file_client_event_proto_depIdxs,
		MessageInfos:      file_client_event_proto_msgTypes,
	}.Build()
	File_client_event_proto = out.File
	file_client_event_proto_goTypes = nil
	file_client_event_proto_depIdxs = nil
}
