// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.1
// source: client.proto

package pbclient

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client source resource reference: pkg/dal/table/client.go
type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Spec          *ClientSpec            `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Attachment    *ClientAttachment      `protobuf:"bytes,3,opt,name=attachment,proto3" json:"attachment,omitempty"`
	MessageType   string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Client) GetSpec() *ClientSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Client) GetAttachment() *ClientAttachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *Client) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

// ClientSpec source resource reference: pkg/dal/table/client.go
type ClientSpec struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion             string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Ip                        string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Labels                    string                 `protobuf:"bytes,3,opt,name=labels,proto3" json:"labels,omitempty"`
	Annotations               string                 `protobuf:"bytes,4,opt,name=annotations,proto3" json:"annotations,omitempty"`
	FirstConnectTime          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=first_connect_time,json=firstConnectTime,proto3" json:"first_connect_time,omitempty"`
	LastHeartbeatTime         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_heartbeat_time,json=lastHeartbeatTime,proto3" json:"last_heartbeat_time,omitempty"`
	OnlineStatus              string                 `protobuf:"bytes,7,opt,name=online_status,json=onlineStatus,proto3" json:"online_status,omitempty"`
	Resource                  *ClientResource        `protobuf:"bytes,8,opt,name=resource,proto3" json:"resource,omitempty"`
	CurrentReleaseId          uint32                 `protobuf:"varint,9,opt,name=current_release_id,json=currentReleaseId,proto3" json:"current_release_id,omitempty"`
	TargetReleaseId           uint32                 `protobuf:"varint,10,opt,name=target_release_id,json=targetReleaseId,proto3" json:"target_release_id,omitempty"`
	ReleaseChangeStatus       string                 `protobuf:"bytes,11,opt,name=release_change_status,json=releaseChangeStatus,proto3" json:"release_change_status,omitempty"`
	ReleaseChangeFailedReason string                 `protobuf:"bytes,12,opt,name=release_change_failed_reason,json=releaseChangeFailedReason,proto3" json:"release_change_failed_reason,omitempty"`
	FailedDetailReason        string                 `protobuf:"bytes,13,opt,name=failed_detail_reason,json=failedDetailReason,proto3" json:"failed_detail_reason,omitempty"`
	ClientType                string                 `protobuf:"bytes,14,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	CurrentReleaseName        string                 `protobuf:"bytes,15,opt,name=current_release_name,json=currentReleaseName,proto3" json:"current_release_name,omitempty"`
	SpecificFailedReason      string                 `protobuf:"bytes,16,opt,name=specific_failed_reason,json=specificFailedReason,proto3" json:"specific_failed_reason,omitempty"`
	TargetReleaseName         string                 `protobuf:"bytes,17,opt,name=target_release_name,json=targetReleaseName,proto3" json:"target_release_name,omitempty"`
	TotalSeconds              float64                `protobuf:"fixed64,18,opt,name=total_seconds,json=totalSeconds,proto3" json:"total_seconds,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ClientSpec) Reset() {
	*x = ClientSpec{}
	mi := &file_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSpec) ProtoMessage() {}

func (x *ClientSpec) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSpec.ProtoReflect.Descriptor instead.
func (*ClientSpec) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *ClientSpec) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ClientSpec) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ClientSpec) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

func (x *ClientSpec) GetAnnotations() string {
	if x != nil {
		return x.Annotations
	}
	return ""
}

func (x *ClientSpec) GetFirstConnectTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstConnectTime
	}
	return nil
}

func (x *ClientSpec) GetLastHeartbeatTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatTime
	}
	return nil
}

func (x *ClientSpec) GetOnlineStatus() string {
	if x != nil {
		return x.OnlineStatus
	}
	return ""
}

func (x *ClientSpec) GetResource() *ClientResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ClientSpec) GetCurrentReleaseId() uint32 {
	if x != nil {
		return x.CurrentReleaseId
	}
	return 0
}

func (x *ClientSpec) GetTargetReleaseId() uint32 {
	if x != nil {
		return x.TargetReleaseId
	}
	return 0
}

func (x *ClientSpec) GetReleaseChangeStatus() string {
	if x != nil {
		return x.ReleaseChangeStatus
	}
	return ""
}

func (x *ClientSpec) GetReleaseChangeFailedReason() string {
	if x != nil {
		return x.ReleaseChangeFailedReason
	}
	return ""
}

func (x *ClientSpec) GetFailedDetailReason() string {
	if x != nil {
		return x.FailedDetailReason
	}
	return ""
}

func (x *ClientSpec) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *ClientSpec) GetCurrentReleaseName() string {
	if x != nil {
		return x.CurrentReleaseName
	}
	return ""
}

func (x *ClientSpec) GetSpecificFailedReason() string {
	if x != nil {
		return x.SpecificFailedReason
	}
	return ""
}

func (x *ClientSpec) GetTargetReleaseName() string {
	if x != nil {
		return x.TargetReleaseName
	}
	return ""
}

func (x *ClientSpec) GetTotalSeconds() float64 {
	if x != nil {
		return x.TotalSeconds
	}
	return 0
}

// ClientAttachment source resource reference: pkg/dal/table/client.go
type ClientAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	BizId         uint32                 `protobuf:"varint,2,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	AppId         uint32                 `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAttachment) Reset() {
	*x = ClientAttachment{}
	mi := &file_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAttachment) ProtoMessage() {}

func (x *ClientAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAttachment.ProtoReflect.Descriptor instead.
func (*ClientAttachment) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

func (x *ClientAttachment) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ClientAttachment) GetBizId() uint32 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *ClientAttachment) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

// ClientResource source resource reference: pkg/dal/table/client.go
type ClientResource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage       float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	CpuMaxUsage    float64                `protobuf:"fixed64,2,opt,name=cpu_max_usage,json=cpuMaxUsage,proto3" json:"cpu_max_usage,omitempty"`
	CpuMinUsage    float64                `protobuf:"fixed64,3,opt,name=cpu_min_usage,json=cpuMinUsage,proto3" json:"cpu_min_usage,omitempty"`
	CpuAvgUsage    float64                `protobuf:"fixed64,4,opt,name=cpu_avg_usage,json=cpuAvgUsage,proto3" json:"cpu_avg_usage,omitempty"`
	MemoryUsage    uint64                 `protobuf:"varint,5,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryMaxUsage uint64                 `protobuf:"varint,6,opt,name=memory_max_usage,json=memoryMaxUsage,proto3" json:"memory_max_usage,omitempty"`
	MemoryMinUsage uint64                 `protobuf:"varint,7,opt,name=memory_min_usage,json=memoryMinUsage,proto3" json:"memory_min_usage,omitempty"`
	MemoryAvgUsage uint64                 `protobuf:"varint,8,opt,name=memory_avg_usage,json=memoryAvgUsage,proto3" json:"memory_avg_usage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientResource) Reset() {
	*x = ClientResource{}
	mi := &file_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResource) ProtoMessage() {}

func (x *ClientResource) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResource.ProtoReflect.Descriptor instead.
func (*ClientResource) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

func (x *ClientResource) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ClientResource) GetCpuMaxUsage() float64 {
	if x != nil {
		return x.CpuMaxUsage
	}
	return 0
}

func (x *ClientResource) GetCpuMinUsage() float64 {
	if x != nil {
		return x.CpuMinUsage
	}
	return 0
}

func (x *ClientResource) GetCpuAvgUsage() float64 {
	if x != nil {
		return x.CpuAvgUsage
	}
	return 0
}

func (x *ClientResource) GetMemoryUsage() uint64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ClientResource) GetMemoryMaxUsage() uint64 {
	if x != nil {
		return x.MemoryMaxUsage
	}
	return 0
}

func (x *ClientResource) GetMemoryMinUsage() uint64 {
	if x != nil {
		return x.MemoryMinUsage
	}
	return 0
}

func (x *ClientResource) GetMemoryAvgUsage() uint64 {
	if x != nil {
		return x.MemoryAvgUsage
	}
	return 0
}

// ClientQueryCondition 客户端查询条件
type ClientQueryCondition struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Uid                 string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Ip                  string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Label               []string               `protobuf:"bytes,3,rep,name=label,proto3" json:"label,omitempty"`
	CurrentReleaseName  string                 `protobuf:"bytes,4,opt,name=current_release_name,json=currentReleaseName,proto3" json:"current_release_name,omitempty"`
	TargetReleaseName   string                 `protobuf:"bytes,5,opt,name=target_release_name,json=targetReleaseName,proto3" json:"target_release_name,omitempty"`
	ReleaseChangeStatus []string               `protobuf:"bytes,6,rep,name=release_change_status,json=releaseChangeStatus,proto3" json:"release_change_status,omitempty"`
	Annotations         *structpb.Struct       `protobuf:"bytes,7,opt,name=annotations,proto3" json:"annotations,omitempty"`
	OnlineStatus        []string               `protobuf:"bytes,8,rep,name=online_status,json=onlineStatus,proto3" json:"online_status,omitempty"`
	ClientVersion       string                 `protobuf:"bytes,9,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ClientType          string                 `protobuf:"bytes,10,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	FailedReason        string                 `protobuf:"bytes,11,opt,name=failed_reason,json=failedReason,proto3" json:"failed_reason,omitempty"`
	StartPullTime       string                 `protobuf:"bytes,12,opt,name=start_pull_time,json=startPullTime,proto3" json:"start_pull_time,omitempty"`
	EndPullTime         string                 `protobuf:"bytes,13,opt,name=end_pull_time,json=endPullTime,proto3" json:"end_pull_time,omitempty"`
	ClientIds           []uint32               `protobuf:"varint,14,rep,packed,name=client_ids,json=clientIds,proto3" json:"client_ids,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClientQueryCondition) Reset() {
	*x = ClientQueryCondition{}
	mi := &file_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientQueryCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientQueryCondition) ProtoMessage() {}

func (x *ClientQueryCondition) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientQueryCondition.ProtoReflect.Descriptor instead.
func (*ClientQueryCondition) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

func (x *ClientQueryCondition) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ClientQueryCondition) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ClientQueryCondition) GetLabel() []string {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *ClientQueryCondition) GetCurrentReleaseName() string {
	if x != nil {
		return x.CurrentReleaseName
	}
	return ""
}

func (x *ClientQueryCondition) GetTargetReleaseName() string {
	if x != nil {
		return x.TargetReleaseName
	}
	return ""
}

func (x *ClientQueryCondition) GetReleaseChangeStatus() []string {
	if x != nil {
		return x.ReleaseChangeStatus
	}
	return nil
}

func (x *ClientQueryCondition) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ClientQueryCondition) GetOnlineStatus() []string {
	if x != nil {
		return x.OnlineStatus
	}
	return nil
}

func (x *ClientQueryCondition) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ClientQueryCondition) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *ClientQueryCondition) GetFailedReason() string {
	if x != nil {
		return x.FailedReason
	}
	return ""
}

func (x *ClientQueryCondition) GetStartPullTime() string {
	if x != nil {
		return x.StartPullTime
	}
	return ""
}

func (x *ClientQueryCondition) GetEndPullTime() string {
	if x != nil {
		return x.EndPullTime
	}
	return ""
}

func (x *ClientQueryCondition) GetClientIds() []uint32 {
	if x != nil {
		return x.ClientIds
	}
	return nil
}

// ClientCommonReq request param
type ClientCommonReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BizId             uint32                 `protobuf:"varint,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	AppId             uint32                 `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Search            *ClientQueryCondition  `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	LastHeartbeatTime int64                  `protobuf:"varint,4,opt,name=last_heartbeat_time,json=lastHeartbeatTime,proto3" json:"last_heartbeat_time,omitempty"`
	PullTime          int64                  `protobuf:"varint,5,opt,name=pull_time,json=pullTime,proto3" json:"pull_time,omitempty"`
	IsDuplicates      bool                   `protobuf:"varint,6,opt,name=is_duplicates,json=isDuplicates,proto3" json:"is_duplicates,omitempty"`
	PrimaryKey        string                 `protobuf:"bytes,7,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	ForeignKeys       *structpb.Struct       `protobuf:"bytes,8,opt,name=foreign_keys,json=foreignKeys,proto3" json:"foreign_keys,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientCommonReq) Reset() {
	*x = ClientCommonReq{}
	mi := &file_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCommonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCommonReq) ProtoMessage() {}

func (x *ClientCommonReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCommonReq.ProtoReflect.Descriptor instead.
func (*ClientCommonReq) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{5}
}

func (x *ClientCommonReq) GetBizId() uint32 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *ClientCommonReq) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ClientCommonReq) GetSearch() *ClientQueryCondition {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *ClientCommonReq) GetLastHeartbeatTime() int64 {
	if x != nil {
		return x.LastHeartbeatTime
	}
	return 0
}

func (x *ClientCommonReq) GetPullTime() int64 {
	if x != nil {
		return x.PullTime
	}
	return 0
}

func (x *ClientCommonReq) GetIsDuplicates() bool {
	if x != nil {
		return x.IsDuplicates
	}
	return false
}

func (x *ClientCommonReq) GetPrimaryKey() string {
	if x != nil {
		return x.PrimaryKey
	}
	return ""
}

func (x *ClientCommonReq) GetForeignKeys() *structpb.Struct {
	if x != nil {
		return x.ForeignKeys
	}
	return nil
}

var File_client_proto protoreflect.FileDescriptor

const file_client_proto_rawDesc = "" +
	"\n" +
	"\fclient.proto\x12\bpbclient\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb3\x01\n" +
	"\x06Client\x12 \n" +
	"\x02id\x18\x01 \x01(\rB\x10\x92A\r2\v客户端IDR\x02id\x12(\n" +
	"\x04spec\x18\x02 \x01(\v2\x14.pbclient.ClientSpecR\x04spec\x12:\n" +
	"\n" +
	"attachment\x18\x03 \x01(\v2\x1a.pbclient.ClientAttachmentR\n" +
	"attachment\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\"\xa1\n" +
	"\n" +
	"\n" +
	"ClientSpec\x12A\n" +
	"\x0eclient_version\x18\x01 \x01(\tB\x1a\x92A\x172\x15客户端组件版本R\rclientVersion\x12 \n" +
	"\x02ip\x18\x02 \x01(\tB\x10\x92A\r2\v客户端IPR\x02ip\x12,\n" +
	"\x06labels\x18\x03 \x01(\tB\x14\x92A\x112\x0f客户端标签R\x06labels\x123\n" +
	"\vannotations\x18\x04 \x01(\tB\x11\x92A\x0e2\f附加信息R\vannotations\x12a\n" +
	"\x12first_connect_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x17\x92A\x142\x12首次拉取时间R\x10firstConnectTime\x12i\n" +
	"\x13last_heartbeat_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x1d\x92A\x1a2\x18最后一次拉取时间R\x11lastHeartbeatTime\x12I\n" +
	"\ronline_status\x18\a \x01(\tB$\x92A!2\x1f在线状态：online、offlineR\fonlineStatus\x124\n" +
	"\bresource\x18\b \x01(\v2\x18.pbclient.ClientResourceR\bresource\x12A\n" +
	"\x12current_release_id\x18\t \x01(\rB\x13\x92A\x102\x0e当前版本IDR\x10currentReleaseId\x12?\n" +
	"\x11target_release_id\x18\n" +
	" \x01(\rB\x13\x92A\x102\x0e目标版本IDR\x0ftargetReleaseId\x12x\n" +
	"\x15release_change_status\x18\v \x01(\tBD\x92AA2?最近一次拉取状态：Success、Failed、Processing、SkipR\x13releaseChangeStatus\x12^\n" +
	"\x1crelease_change_failed_reason\x18\f \x01(\tB\x1d\x92A\x1a2\x18发布变更失败原因R\x19releaseChangeFailedReason\x12O\n" +
	"\x14failed_detail_reason\x18\r \x01(\tB\x1d\x92A\x1a2\x18失败详细信息原因R\x12failedDetailReason\x12;\n" +
	"\vclient_type\x18\x0e \x01(\tB\x1a\x92A\x172\x15客户端组件类型R\n" +
	"clientType\x12C\n" +
	"\x14current_release_name\x18\x0f \x01(\tB\x11\x92A\x0e2\f当前版本R\x12currentReleaseName\x12M\n" +
	"\x16specific_failed_reason\x18\x10 \x01(\tB\x17\x92A\x142\x12具体失败原因R\x14specificFailedReason\x12A\n" +
	"\x13target_release_name\x18\x11 \x01(\tB\x11\x92A\x0e2\f目标版本R\x11targetReleaseName\x129\n" +
	"\rtotal_seconds\x18\x12 \x01(\x01B\x14\x92A\x112\x0f变更总耗时R\ftotalSeconds\"\x83\x01\n" +
	"\x10ClientAttachment\x12#\n" +
	"\x03uid\x18\x01 \x01(\tB\x11\x92A\x0e2\f客户端UIDR\x03uid\x12$\n" +
	"\x06biz_id\x18\x02 \x01(\rB\r\x92A\n" +
	"2\b业务IDR\x05bizId\x12$\n" +
	"\x06app_id\x18\x03 \x01(\rB\r\x92A\n" +
	"2\b服务IDR\x05appId\"\x8e\x04\n" +
	"\x0eClientResource\x124\n" +
	"\tcpu_usage\x18\x01 \x01(\x01B\x17\x92A\x142\x12当前cpu使用率R\bcpuUsage\x12;\n" +
	"\rcpu_max_usage\x18\x02 \x01(\x01B\x17\x92A\x142\x12最大cpu使用率R\vcpuMaxUsage\x12;\n" +
	"\rcpu_min_usage\x18\x03 \x01(\x01B\x17\x92A\x142\x12最小cpu使用率R\vcpuMinUsage\x12;\n" +
	"\rcpu_avg_usage\x18\x04 \x01(\x01B\x17\x92A\x142\x12平均cpu使用率R\vcpuAvgUsage\x12=\n" +
	"\fmemory_usage\x18\x05 \x01(\x04B\x1a\x92A\x172\x15当前内存使用率R\vmemoryUsage\x12D\n" +
	"\x10memory_max_usage\x18\x06 \x01(\x04B\x1a\x92A\x172\x15最大内存使用率R\x0ememoryMaxUsage\x12D\n" +
	"\x10memory_min_usage\x18\a \x01(\x04B\x1a\x92A\x172\x15最小内存使用率R\x0ememoryMinUsage\x12D\n" +
	"\x10memory_avg_usage\x18\b \x01(\x04B\x1a\x92A\x172\x15平均内存使用率R\x0ememoryAvgUsage\"\x9a\a\n" +
	"\x14ClientQueryCondition\x12#\n" +
	"\x03uid\x18\x01 \x01(\tB\x11\x92A\x0e2\f客户端UIDR\x03uid\x12 \n" +
	"\x02ip\x18\x02 \x01(\tB\x10\x92A\r2\v客户端IPR\x02ip\x12*\n" +
	"\x05label\x18\x03 \x03(\tB\x14\x92A\x112\x0f客户端标签R\x05label\x12C\n" +
	"\x14current_release_name\x18\x04 \x01(\tB\x11\x92A\x0e2\f当前版本R\x12currentReleaseName\x12A\n" +
	"\x13target_release_name\x18\x05 \x01(\tB\x11\x92A\x0e2\f目标版本R\x11targetReleaseName\x12x\n" +
	"\x15release_change_status\x18\x06 \x03(\tBD\x92AA2?最近一次拉取状态：Success、Failed、Processing、SkipR\x13releaseChangeStatus\x12L\n" +
	"\vannotations\x18\a \x01(\v2\x17.google.protobuf.StructB\x11\x92A\x0e2\f附加信息R\vannotations\x12I\n" +
	"\ronline_status\x18\b \x03(\tB$\x92A!2\x1f在线状态：online、offlineR\fonlineStatus\x12A\n" +
	"\x0eclient_version\x18\t \x01(\tB\x1a\x92A\x172\x15客户端组件版本R\rclientVersion\x12;\n" +
	"\vclient_type\x18\n" +
	" \x01(\tB\x1a\x92A\x172\x15客户端组件类型R\n" +
	"clientType\x12E\n" +
	"\rfailed_reason\x18\v \x01(\tB \x92A\x1d2\x1b客户端失败主类原因R\ffailedReason\x12?\n" +
	"\x0fstart_pull_time\x18\f \x01(\tB\x17\x92A\x142\x12开始拉取时间R\rstartPullTime\x12;\n" +
	"\rend_pull_time\x18\r \x01(\tB\x17\x92A\x142\x12结束拉取时间R\vendPullTime\x12/\n" +
	"\n" +
	"client_ids\x18\x0e \x03(\rB\x10\x92A\r2\v客户端IDR\tclientIds\"\xfa\x03\n" +
	"\x0fClientCommonReq\x12$\n" +
	"\x06biz_id\x18\x01 \x01(\rB\r\x92A\n" +
	"2\b业务IDR\x05bizId\x12$\n" +
	"\x06app_id\x18\x02 \x01(\rB\r\x92A\n" +
	"2\b服务IDR\x05appId\x12I\n" +
	"\x06search\x18\x03 \x01(\v2\x1e.pbclient.ClientQueryConditionB\x11\x92A\x0e2\f搜索条件R\x06search\x12A\n" +
	"\x13last_heartbeat_time\x18\x04 \x01(\x03B\x11\x92A\x0e2\f心跳时间R\x11lastHeartbeatTime\x124\n" +
	"\tpull_time\x18\x05 \x01(\x03B\x17\x92A\x142\x12拉取趋势时间R\bpullTime\x12B\n" +
	"\ris_duplicates\x18\x06 \x01(\bB\x1d\x92A\x1a2\x18拉取趋势是否去重R\fisDuplicates\x12>\n" +
	"\vprimary_key\x18\a \x01(\tB\x1d\x92A\x1a2\x18区分标签的主维度R\n" +
	"primaryKey\x12S\n" +
	"\fforeign_keys\x18\b \x01(\v2\x17.google.protobuf.StructB\x17\x92A\x142\x12副维度的数据R\vforeignKeysBFZDgithub.com/TencentBlueKing/bk-bscp/pkg/protocol/core/client;pbclientb\x06proto3"

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData []byte
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)))
	})
	return file_client_proto_rawDescData
}

var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_client_proto_goTypes = []any{
	(*Client)(nil),                // 0: pbclient.Client
	(*ClientSpec)(nil),            // 1: pbclient.ClientSpec
	(*ClientAttachment)(nil),      // 2: pbclient.ClientAttachment
	(*ClientResource)(nil),        // 3: pbclient.ClientResource
	(*ClientQueryCondition)(nil),  // 4: pbclient.ClientQueryCondition
	(*ClientCommonReq)(nil),       // 5: pbclient.ClientCommonReq
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 7: google.protobuf.Struct
}
var file_client_proto_depIdxs = []int32{
	1, // 0: pbclient.Client.spec:type_name -> pbclient.ClientSpec
	2, // 1: pbclient.Client.attachment:type_name -> pbclient.ClientAttachment
	6, // 2: pbclient.ClientSpec.first_connect_time:type_name -> google.protobuf.Timestamp
	6, // 3: pbclient.ClientSpec.last_heartbeat_time:type_name -> google.protobuf.Timestamp
	3, // 4: pbclient.ClientSpec.resource:type_name -> pbclient.ClientResource
	7, // 5: pbclient.ClientQueryCondition.annotations:type_name -> google.protobuf.Struct
	4, // 6: pbclient.ClientCommonReq.search:type_name -> pbclient.ClientQueryCondition
	7, // 7: pbclient.ClientCommonReq.foreign_keys:type_name -> google.protobuf.Struct
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
